### ISSUE TITLE
Footer information

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1003]
**Description**:
The 'Privacy policy' link in the footer is pointing to the data policy. We should replace this by two links: 
- 'Privacy statement' pointing to information such as the one at: https://stfc.ukri.org/about-us/privacy-statement/
- 'Data policy' pointing to the ISIS data policy

Have we lost the link to the contact page?

**Acceptance criteria**:
- [ ] Check links in the footer

**Comment by joshuadkitenge** [comment]
![Screenshot 2021-12-14 090028](https://user-images.githubusercontent.com/83226114/145966569-6dcd5f0c-fff7-423e-9811-2778864ffca3.png)

**Comment by agbeltran** [comment]
that looks good, @joshuadkitenge, thanks!

**Comment by joelvdavies** [comment]
This was closed in https://github.com/ral-facilities/scigateway/pull/880.
