### ISSUE TITLE
Homepage headings need adjusting

### ISSUE THREAD

**Issue by mattjSTFC** [ral-facilities/datagateway#1007]
**Description**:
On the main page of DG there needs to be a hierarchy for the headings to aid readability and to give an indication of the most important journey. At the moment the card headings are all the same size so give the perception they are weighted the same. 

- "Browse, explore and visualise..." should ideally be 32px
- Search, Download and "ISIS Neutron and..." should be 24px

This way the hierarchy on the main page flows from hero banner, main introduction with primary call to action followed by secondary journeys.

**Acceptance criteria**:
- [ ] GIVEN finding out more information about DataGateway WHEN looking at the homepage content sections THEN the headings should show me where to go next

**Comment by agbeltran** [comment]
The order in the menu should also match, so we need to put Search first and Download later. Thanks!
