### ISSUE TITLE
Filters applied when switching to another search tab

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1008]
**Description**:
After a search is performend, and a filter applied to one of the results tabs, the same filter is applied when switching to another tab.

Steps to reproduce:
1. go to search and include 'battery' as a query string, hit search
2. in the investigation tab, in the Title filter, select Exclude and filter excluding 'structure'
3. then go to the Dataset tab
4. 400 error - bad request - is raised

**Acceptance criteria**:
- [ ] Fix filters between search results tab, consider what happens if user gets back to original search tab

**Comment by louise-davies** [comment]
separate the filter params into "investigation"/"dataset"/"datafile" filter params perhaps?
