### ISSUE TITLE
Search overflows when sidebar is open

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1023]
**Description**:
![image](https://user-images.githubusercontent.com/22525471/146404020-cbf27f1a-d82b-4d65-85ea-f7f114ae5137.png)

Due to the sidebar changes - it seems like the search page is too wide and doesn't adjust based on the sidebar width

**Acceptance criteria**:
- [ ] datagateway-search doesn't overflow when the sidebar is open

**Comment by joelvdavies** [comment]
I believe this happened even before the sidebar changes, the main app bar always resized based on the navigation drawer but no such logic occurs for the plugins. e.g. search just uses a width of '98vw' which pushes everything out.

**Comment by joelvdavies** [comment]
Something I just noticed when I changed one of the div's width to 100% via inspect, the issue was fixed but at the cost of performance. The resizing of the table in search makes everything quite juddery compared to other views.

**Comment by AkhilMag13** [comment]
> Something I just noticed when I changed one of the div's width to 100% via inspect, the issue was fixed but at the cost of performance. The resizing of the table in search makes everything quite juddery compared to other views.

I have noticed this problem where the SciGateway's Header and the Footer are not scaling fully to the DG Search page size.
![image](https://user-images.githubusercontent.com/88283659/146576980-4428fa3f-1e83-40ca-8542-456ae528e099.png)

![image](https://user-images.githubusercontent.com/88283659/146576940-47eb1a50-1a78-42cd-be8e-bc05b6d85437.png)

**Comment by joelvdavies** [comment]
Without table resizing:
![search-overflow](https://user-images.githubusercontent.com/90245114/148051481-6fecb5f9-1ee9-4c80-9bca-80a5776a0e54.gif)
With table resizing:
![search-overflow-lag](https://user-images.githubusercontent.com/90245114/148051470-ebb16daf-bc0a-4832-affc-2eb5b18fdd73.gif)

Even when recording these gifs at 60fps the lag seems hard to see. It does gets worse on higher resolution screens, I used 1440p, but overall I agree with Louise - the performance cost is worth it to fix the issue for now.
