### ISSUE TITLE
Search filters show when entering a search term but no searched performed

### ISSUE THREAD

**Issue by mattjSTFC** [ral-facilities/datagateway#1025]
**Description**:
When entering a search term the filter options are shown which is unexpected behavior as an action wasn't performed and not something I was expecting to see when filling out the field. See below:

https://user-images.githubusercontent.com/56403718/146530263-7e133636-f6bc-44bb-9f3c-b44a0f126891.mp4

**Acceptance criteria**:
- [ ] Filters should remain hidden until usable

**Comment by agbeltran** [comment]
thank you, @mattjSTFC ! Unfortunately I cannot see the video (it says that the file is corrupt). Could you please upload it again? Thanks

**Comment by mattjSTFC** [comment]
It seems to play fine for me 🤔

**Comment by agbeltran** [comment]
thanks for checking! I tried in Chrome and I can see it. In Firefox, I still see the error message "Video can't be played because the file is corrupt". I'll use Chrome to check it. Thanks

**Comment by mattjSTFC** [comment]
Oh, that's good to know. I had only checked in Chrome
