### ISSUE TITLE
Check DLS footer links

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1030]
**Description**:
So that they cover what we have in Topcat now

**Acceptance criteria**:
- [ ] Updated footer links for DLS

**Comment by louise-davies** [comment]
These are the current TopCAT links:
![image](https://user-images.githubusercontent.com/22525471/152335907-a6135384-ee35-48a1-b85f-e8ce066541c2.png)

These are the current DG links:
![image](https://user-images.githubusercontent.com/22525471/152335989-8e23e6ac-4ecc-4a0b-b963-fb216942fee5.png)

DLS link links to same page. We don't have an about us link, but on the homepage we link to the about us page in the facility card. It's also the first header in the DLS homepage which we do link to.

The privacy statement link in TopCAT links to the Diamond privacy policy, which includes it's own cookie policy. We could link to the DLS privacy policy page in our cookie management page?

Cookie policy links to the correct things.

And finally we moved our contact button to the footer with the correct `mailto` link, as well as adding a direct link to the DLS data policy page.

It's not hard at all to configure these if needed.

**Comment by agbeltran** [comment]
Let's follow the same approach as in Topcat for now and we will consult DLS at the next meeting

**Comment by agbeltran** [comment]
@louise-davies please update here with the screenshot of the new DG links
