### ISSUE TITLE
Homepage tweaks

### ISSUE THREAD

**Issue by mattjSTFC** [ral-facilities/datagateway#1048]
**Description**:
Minor changes are required to the homepage to tidy up the recent update. These include:

**Footer**

- [x] Remove the underlines and have them only appear on hover. This matches how other links are styled in the platform
- [x] A font family needs to be applied as it not using Roboto
- [x] I think, from inspecting the site, that spacing works as 4px, 8px, 16px, 24px and so on. With this in mind can the padding for the footer container be updated to have an 8px spacing (top and bottom) instead of 14px. Left and right spacing needs to be set to 16px. This then matches the side bar navigation spacing and improves the alignment. 

![image](https://user-images.githubusercontent.com/56403718/148530654-a3322bd0-62a0-4270-baa9-f121e57aca45.png)

**Side bar**

- [x] The links in the side bar have an extra space added which needs to be removed so the text aligns to the link headings: Browse and Discover:

![image](https://user-images.githubusercontent.com/56403718/148531256-6ced49d6-8404-4beb-ba01-f20de56d2f23.png)

- [x] Can the Browse heading have padding top set to 16px instead of 8px? This creates a consistent space (top and left) around the headings and links
- [x] Can the STFC logo have padding left 16px set? This again will align it to the footer and side bar links

**Top navigation**

- [x] Can the spacing between the burger menu icon and the DataGateway logo be reduced? The current gap does look odd. Below shows a 16px gap

![image](https://user-images.githubusercontent.com/56403718/148532930-34e92985-c202-4e4b-a40a-bb66dcde5b72.png)

- [x] Padding-top 3px has been added to the help text link. Can this be removed so it aligns correctly with the logo? The Help link and help icon still needs to be reconsidered but this is for another day
- [x] The spacing on the main container could also be reduced to 16px from 24px but I am not familiar with the UI components so there maybe a responsive requirement to keep as is. Maybe something to check with Louise but it would then match the alignment of the side bar and footer
- [x] The bell icon has some styling missing (8px left and right) which would match the help and settings icons. It looks odd at the moment as the spacing to the "Sign in" button is not consistent:

![image](https://user-images.githubusercontent.com/56403718/148534293-6c1c44b3-d1ce-4d16-814f-5b537174000c.png)

**Cards**

- [x] Really minor but there is a spacing inconsistency between the last paragraph element and button in the cards. The main card has a 16px gap but Search and Download have a 32px gap

![image](https://user-images.githubusercontent.com/56403718/148536406-b3f1cc46-8321-4bd4-9923-ab7a2db13eaa.png)

**Buttons**

- [x] This may need further discussion but it does feel unbalanced that the side bar links and button call to actions are either sentence case or uppercase. I would personally make them sentence case as less intimidating. 
- [x] The font weight is also different. Sign in is 400 and the other buttons in the cards are 500. Maybe they should all be set to 500  so they stand out from any block textual content

**ISIS Neutron and Muon Source card**

- [x] The colour of the text is grey and should be white

This is how it could look with most of the changes applied:

![datagateway isis stfc ac uk_datagateway (3)](https://user-images.githubusercontent.com/56403718/148535911-f07ddc6f-8f44-4830-8437-083ddfa48655.png)

**Comment by joelvdavies** [comment]
Here is a screenshot after applying the changes: 
![image](https://user-images.githubusercontent.com/90245114/148749169-9d9d1512-38b6-431f-a525-03f2057475b1.png)

**Comment by mattjSTFC** [comment]
Hi @joelvdavies looks good! Out of interest what is the spacing between the nav icon and logo?

**Comment by joelvdavies** [comment]
@mattjSTFC That is 16px.

**Comment by mattjSTFC** [comment]
Wow it looks bigger but I think that's just an illusion as the icon probably has spacing around it. Thanks for looking at the updates 👍 Looks nice and tidy now 😃
