### ISSUE TITLE
Display "No publications" in the landing page for investigations

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1053]
**Description**:
We had dealt with "No publications" in the detailed view of an investigation (in the card list or table) in issue https://github.com/ral-facilities/datagateway/issues/982 (see e.g. second investigation at: https://datagateway.isis.stfc.ac.uk/browse/instrument/79797880/facilityCycle/87730661/investigation?view=table&sort={%22startDate%22%3A%22desc%22}) 

However, we still have an empty title in the landing page for investigations: https://datagateway.isis.stfc.ac.uk/browse/instrument/79797880/facilityCycle/87730661/investigation/99714108?view=table

Add "No publications" under the header "Publications" in the landing page view too. 

**Acceptance criteria**:
- [x] Add "No publications" under the header "Publications" in the landing page view

**Comment by AkhilMag13** [comment]
During testing for 'No Publications' I found that this issue can also be replicated with samples and users too. So I have implemented a fix for both of these in c6fba5c
