### ISSUE TITLE
Sort DLS proposal views by title or name rather than by ID

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1084]
**Description**:
Normally, we sort by ID on every request to ensure the database returns results in a deterministic order so the data can be paginated, but sorting on a field not returned by distinct causes missing results. @MRichards99 found that we can fix both problems by instead sorting on one of the two `distinct`ed fields (i.e. `title` and `name`). I'd say `title` looks nicer to sort on in DLS data but either is fine.

This also means theoretically we could reintroduce filters on these views - but they would work quite weirdly as you *need* to sort by at least one of the two fields, so you couldn't have both be null. This may be more effort to implement than it's worth, and perhaps should be a different issue.

**Acceptance criteria**:
- [ ] DLS proposal views are sorted by `title` or `name` rather than `id`

**Comment by joelvdavies** [comment]
@louise-davies I agree about creating a separate issue for reintroducing the sorting options, I feel this would need some discussion due to the weird behaviour.
