### ISSUE TITLE
Cart for selection is not visible in search results page

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1092]
**Description**:
The search page is not showing the cart at the top, so when selecting some items, it is only possible to see that the warning selection has been updated, but not the summary/total number of selected items as shown for other views.

It would be good to harmonise this.

Related to #1031 

<img width="1876" alt="Screenshot 2022-01-28 at 17 24 05" src="https://user-images.githubusercontent.com/1417033/151593179-2779f8a5-897e-4608-a5be-80d7414dba86.png">

**Acceptance criteria**:
- [ ] Show selection cart in search view

**Comment by louise-davies** [comment]
Add cart button to the end of the tabs bar
