### ISSUE TITLE
Add functionality to "Calculate file size" button in DLS detail panels

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#118]
Due to the fact that when details panels were implemented, the `getSize` functionality hadn't been added, these buttons currently do nothing. Now we have handled the `getSize` functionality for ISIS tables, this call should be triggered as a result of clicking the calculate button in the `DLSDatasetDetailsPanel` & `DLSVisitDetailsPanel`.

Acceptance criteria:
- Clicking "Calculate" button in a details panel in the DLS Visits or Datasets table actually sends a `getSize` request and updates the panel with the size.

**Comment by GoelBiju** [comment]
I noticed now, @louise-davies and @tswinb , that the facility name in `datagateway-table` has been hardcoded into the getSize calls in `investigations.tsx` and `datasets.tsx`. Maybe this could be something that could be edited with this issue.

At the time there was no facility name included in the `datagateway-table-settings.json` and now there is. We should use the facilityName from the settings.

**Comment by GoelBiju** [comment]
https://github.com/ral-facilities/datagateway/issues/118#issuecomment-599564781 will be addressed in #127.
