### ISSUE TITLE
Display warning to user if they exceed number of file/total size limits

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1183]
**Description**:
TopCAT displays a warning like so:

![image](https://user-images.githubusercontent.com/22525471/160371182-998c26c0-8e54-410b-923e-3589b8358880.png)

We should also display a warning (either via a notification or like an error message similar to TopCAT) to the user in addition to disabling the button

**Acceptance criteria**:
- [ ] If user has exceeded maximum file count/file size limits, then a warning is visually displayed to the user that they have exceeded a limit

**Comment by zshawdev** [comment]
Hello @louise-davies, I'd like to help with this one! Would I be able to get assigned to it?
