### ISSUE TITLE
Individually downloading empty (0 bytes) files redirects to broken IDS download page

### ISSUE THREAD

**Issue by sam-glendenning** [ral-facilities/datagateway#1195]
**Description**:
As per [this change](https://github.com/ral-facilities/datagateway/pull/1192), users can no longer download all items in their selections if their selections include an empty file (size of 0 B). In this case, they are presented with a warning message above the download button, which is disabled until they remove the offending selection(s).

However, users can still individually attempt to download these files in Dataview, which results in a redirect to a broken IDS download page, presumably because the file does not exist or is impossible to download in whatever form it exists. We want to prevent the user from doing this if the file is empty. Perhaps either disable or remove the download button? It may also be helpful to provide the user with some information on why they cannot download the file, similarly to the selections cart. Perhaps this could come in the form of a tooltip which displays when the user hovers the mouse over a disabled download button?

**Acceptance criteria**:
- [ ] User can no longer download empty files in table or card view
- [ ] Check site-wide that they are no more possible methods of initiating a download of an empty file

**Comment by louise-davies** [comment]
I'd just say to disable the button and maybe add a tooltip saying why it's disabled
