### ISSUE TITLE
Check whether a download type is disabled in DownloadConfirmation

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#120]
Admins can disable download types and so we need some way of stopping a user from submitting to a disabled download type and displaying a message to the user to describe why it is disabled.

TopCAT currently does this after the user clicks OK - but this is potentially confusing behaviour and perhaps a better way is telling the user before they try to submit their download. We would still need to be able to "select" a download in order to display the disabled reasoning message - so perhaps we should allow the option to be selected and display the message and disable the submit button.

See relevant TopCAT code: https://github.com/icatproject/topcat/blob/master/yo/app/scripts/controllers/download-cart.controller.js#L110

Acceptance criteria:
- [x] A user is not able to submit downloads to a download type that is disabled
- [x] A message is displayed to the user explaining that the download type is disabled or a custom message set on the download type status itself.
- [x] Ideally a better UX solution than TopCAT in that the user can tell that a download type is disabled before clicking the OK button.

**Comment by GoelBiju** [comment]
At the moment there is a slight issue regarding how to have the component sort the access methods once all the status information has been received. This is mainly due to the fact that the requests are made in an asynchronous function and that the updated state of the accessMethod object is not instantly available.

**Comment by GoelBiju** [comment]
At the moment a download type can be enabled by altering the response from the status request and submitting a download request using the disabled download type does not return an error but instead creates a download (returning a download id). I am not sure if this is an intended feature or not @louise-davies .

**Comment by GoelBiju** [comment]
I have added the `examples.json` Cypress fixture file that is automatically created when running in interactive mode for e2e tests to the gitignore. This issue will be resolved by Cypress but can be found [here](https://github.com/cypress-io/cypress/issues/2715).

**Comment by louise-davies** [comment]
@GoelBiju 
> At the moment a download type can be enabled by altering the response from the status request and submitting a download request using the disabled download type does not return an error but instead creates a download (returning a download id). I am not sure if this is an intended feature or not @louise-davies .
> 
> I have mentioned this issue to @stuartpullinger .

I think the way that the method of disabling download types was added in just to prevent the UI from allowing users to submit requests, and not preventing a download request itself if the download type is disabled. This can perhaps me made into an issue in the TopCAT Java side repo, if this stricter behaviour is required.
