### ISSUE TITLE
Improve error message when session expires for anonymous user

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1209]
**Description**:
At the moment, we have "Unable to find user by sessionid: <session uuid>" as a message for anonymous users when the session expires. It would be better to say "Your session has expired, please reload the page" or something similar. If useful for reporting issues, do add the sessionid too into the message, after a more user-friendly message as before.

<img width="1374" alt="Screenshot 2022-04-04 at 18 23 15" src="https://user-images.githubusercontent.com/1417033/161693648-c643b3b3-78bf-4e16-9471-43e63f746bed.png">

**Acceptance criteria**:
- [ ] Add user-friendly message when session expires

**Comment by sam-glendenning** [comment]
"Your session has expired. Please try logging in again" or something along those lines
