### ISSUE TITLE
Convert lucene query call to Redux action

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#121]
Separation of concerns between the search call and the UI elements.

**Comment by GoelBiju** [comment]
Recalling what @louise-davies [mentioned](https://github.com/ral-facilities/datagateway/pull/112#issuecomment-590861025) for the data-search branch, specifically we need to:

- [ ] move Lucene API calls to a redux action (in datagateway-common),

- [ ] extract out query parameter builder.

- [ ]
