### ISSUE TITLE
Errors when multi selecting items for the cart

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1210]
**Description**:
> During the selection of large number of datasets or large number of files (using shift key and scrolling up or down) I received a network error.
> ![image](https://user-images.githubusercontent.com/22525471/161974209-413ac3fa-d89a-4622-8b38-e0e4ce2640ac.png)
> And showing the same when selecting many datafiles:
> ![image](https://user-images.githubusercontent.com/22525471/161974222-8eea511a-671c-48f7-96d7-e3f146366e83.png)

**Acceptance criteria**:
- [ ] TDB - awaiting demo of issue

**Comment by louise-davies** [comment]
I believe the problem is shift-click removing many files, as the HTTP request is a DELETE with the IDs to be removed in the query params, we exceed the max length for a HTTP request (error 414 Request-URI Too Long/ ns error dom bad URI). I can’t seem to shift-unclick on TopCAT – so either we revert this functionality to be on par with TopCAT behaviour, or we change the request to be a POST request with an extra param to say whether we’re adding or removing items from the cart. I can bump up the request limit size in Apache (LimitRequestLine 1000000 LimitRequest-FieldSize 1000000), but eventually I think browsers will complain and refuse to process as well… also TopCAT errors out, even if Apache & the browser will process a request that long top-cat doesn’t.

**Comment by louise-davies** [comment]
The best long term solution is to:
> change the [remove items from cart] request to be a POST request with an extra param to say whether we’re adding or removing items from the cart

We can add an extra form parameter to the POST request to the cart, which is something like `method: "add" / "remove"` or `remove: true / false`. We could make this change backwards compatible by ensuring the default is for the POST request to assume adding to the cart, and keeping the old DELETE endpoint.

@agbeltran Above is the thoughts I have had about modifying the TopCAT server side. @MRichards99 Alejandra mentioned that perhaps this is something you could look into?

**Comment by MRichards99** [comment]
@louise-davies yes I can look at this. How urgent is this - do you want me to start looking at the start of next week?

I've not worked on TopCAT/the download API before, so some beginner questions:
- I'm guessing you're referring to the [/cartItems](https://repo.icatproject.org/site/topcat/2.4.7/miredot/index.html#-1949990938) endpoint that has both POST and DELETE methods on?
- In terms of implementation, if the input for the form parameter is remove/false, then I just call the methods that the DELETE request calls?
- Will this just need to be implemented on the download-api, or actual TopCAT too? I haven't really followed the activity of those repos so just want to confirm what we do with them these days
- If you could confirm what you'd like the additional parameter to look like, that would be good. I don't have any preference between those two suggested above so whichever is easier for you/DataGateway
- Will tests need to be added for this new form parameter?

**Comment by louise-davies** [comment]
This is a fairly big issue so it would be good to get solved soon-ish

Yes I am referring to the `/cartitems` endpoint, as that's in charge of adding and removing items to the cart

Yes the methods being called need to be the same, the issue is with the request being a DELETE and not a POST (and thus causing issues with the length of the URL because the IDs are put in the query params rather than the POST body)

It probably needs to be implemented on both, as we anticipate at first releasing DG alongside TopCAT in case there are any issues after releasing.

I don't really have a preference and it doesn't really matter - the Boolean is probably better as it reflects there are two choices, but do look and see if there are any best practices.

I wouldn't bother adding tests if there aren't any already, but if there are for that function then it would be good to have the tests updated.

**Comment by agbeltran** [comment]
thanks @louise-davies for investigating the issue in detail, @MRichards99 - it would be great if you could start investigating the Topcat back-end / download-api to see how to implement the POST method; we can discuss about priorities w.r.t. OG work

**Comment by MRichards99** [comment]
I have created PRs for the backend side of this at https://github.com/icatproject/topcat/pull/483 and https://github.com/ral-facilities/datagateway-download-api/pull/12
