### ISSUE TITLE
DLS logos

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1212]
**Description**:
For the DLS instance, we have the DLS logo at the top instead of the DataGateway logo and the STFC logo in the bottom left. 

I would keep the DataGateway logo at the top and include the DLS logo at the bottom left. To be discussed to DLS, but we should follow the same approach for all our instances.

**Acceptance criteria**:
- [ ] Change logos in DLS instance

**Comment by louise-davies** [comment]
Only implement this change once #1219 is done

**Comment by sam-glendenning** [comment]
May be able to tackle this at the same time - https://github.com/ral-facilities/datagateway/issues/1256

**Comment by louise-davies** [comment]
We got feedback from DLS comms and actioned it
