### ISSUE TITLE
Add e2e tests to datagateway-search

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#122]
Emily didn't have time to finish making e2e tests for datagateway-search, so these still need to be made.

Acceptance criteria:
- [ ] e2e tests that test the functionality of datagateway-search are written.

**Comment by tswinb** [comment]
Last commit (10th June) adds date test to the datafile tab which should complete the set of tests for each search tab (each has a text search test, a date search test and a checkbox test)
