### ISSUE TITLE
KeyboardDateTimePicker can't enter in seconds

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1227]
**Description**:
We think this is fixed by MUIv5?

User should be able to select seconds by keyboard input and through the GUI.

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by sam-glendenning** [comment]
According to documentation, MUIv5 supports seconds - see https://mui.com/x/api/date-pickers/date-time-picker/

**Comment by sam-glendenning** [comment]
@LunaBarrett now that I've finished the work I told you about on https://github.com/ral-facilities/datagateway/pull/1339, you should be free to give this a go :)
