### ISSUE TITLE
Rename package datagateway-table to datagateway-dataview

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#127]
As we are adding other views, in addition to table view, we are renaming the package ```datagateway-table``` to ```datagateway-dataview```

**Comment by GoelBiju** [comment]
It is worth noting to use `git mv` when renaming/moving files or folders as it makes it a lot easier than doing it manually. There is a good article relating to this [here](https://www.patrick-wied.at/blog/rename-files-and-folders-with-git).

**Comment by GoelBiju** [comment]
https://github.com/ral-facilities/datagateway/issues/118#issuecomment-599564781 is addressed by https://github.com/ral-facilities/datagateway/commit/7f4e21fa83df1b7b128334af2bf937396cce7bb4.
