### ISSUE TITLE
Create card/grid view for generic entities

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#128]
Create a component to visualise different entities in a grid/card view. This component will be in the ```datagateway-dataview``` package.

This card view needs to be paginated. 

We will customise it for specific entities such as investigations and datasets (and there will be separate issues for those). 

This relates to https://github.com/ral-facilities/datagateway-userstories/issues/110

Acceptance criteria
- [x] A generic card view for entities supporting pagination.

**Comment by GoelBiju** [comment]
Here is the [browse datagateway user story](https://github.com/ral-facilities/datagateway-userstories/issues/12) which shows some examples of card/grid views posted by @agbeltran.

**Comment by GoelBiju** [comment]
So initial plan is to create a single card component. This will involve:

- Figuring out how to use CSS3 Flexbox (or make use of Grids?); the current approach is to try flexbox (this will be a single **EntityCard** component - maybe needs a better name)
- Create these InfoCard's dynamically based on the number of investigations/datasets that are in the state and show this in an external **CardView** component

An initial mockup of a single card is the following:

![image](https://user-images.githubusercontent.com/16869075/77157221-d50a0b80-6a98-11ea-8d87-02e2643efd74.png)

This is the [initial Balsamiq mockup](https://stfc.mybalsamiq.com/projects/datagateway-dataview/datagateway-dataview) that I am working of for the whole `datagateway-dataview` and will be changed when required.

**Comment by GoelBiju** [comment]
This can be updated when needed but other components of the **CardView** component include:

- pagination,
- filtering/searching options

We will also need to make this component generic, similar to how the *Table* component works and just provide data to it and customise how it can be displayed for different entities (investigation/datasets).

**Comment by GoelBiju** [comment]
At the moment I can start working with the investigation data. Similar to the Table component, the **CardView** should be able to accept props such as *data*, *onClick*, *sort*/*onSort* and *check*/*onCheck* in order to be customisable for different entities (i.e. investigations/datasets).

This CardView can then be used in custom card components e.g. *InvestigationCardView*/*DatasetCardView* but this will require more customisable in terms of layout.

The current priority is to:

- [ ] Fetch investigation data in a separate component and pass data into *CardView* to dynamically generate the **EntityCard's** based on the number of investigations/datasets that are in the state and render this via the **CardView** component.

**Comment by GoelBiju** [comment]
Ignore https://github.com/ral-facilities/datagateway/commit/6fef79a233fc93da79e6d4df9d52ad0a09e882f0 as it is only related with #162 (this commit has been renamed for that branch).

**Comment by GoelBiju** [comment]
There are some items to fix, this includes:

- [ ] after toggling the view, the card information fails to load (**work out why this occurs**),

- [ ] fix the image sizing when there are thumbnails,

- [ ] the arrow tooltip needs to be generalised into separate wrapping components and not have features such as `percentageWidth`/`maxEnabledHeight` in the normal component (move to a separate component e.g. `CardTooltip`),

- [ ] the collapsible component and "Show more"/"Show less" should not be present if the description does not exceed the default maximum content width (100px - this can be changed if needed),

- [ ] the "No description available" should be centered on the card if there is no summary available.

**Comment by GoelBiju** [comment]
Additional features for the Card and CardView (arising from sprint planning and remaining tasks):

- [ ] the toggled view should be saved to localStorage (retained for later use) so the user can continue using the same view as before,

- [ ] query parameters should be used for view type (table/card), sorting, pagination and filtering,

- [ ] toggle (*Switch* component) button requires names for table/card,

- [ ] instruments could possibly used as tags (this is an idea for now),

- [ ] search box (with dropdown advanced search).

**Comment by GoelBiju** [comment]
The updated mockup for the whole CardView includes the add/remove from cart buttons and search box: 

![image](https://user-images.githubusercontent.com/16869075/80608640-fadae680-8a2e-11ea-9df3-bd9eab55ad3a.png)

**Comment by GoelBiju** [comment]
To accomdate different data and to show less information for certain entities, we may need to check that the card layout works well when you have less information provided i.e. when there are no tags, no further information.

Also the card needs to support for entities which may not be items to add to cart but more links to further information, so the add/remove to/from cart may not be present.

**Comment by GoelBiju** [comment]
A feature that needs to be implemented is filtering. At the moment querying for ISIS means that we cannot use the distinct option to get only the data we need, meaning all data is fetched when we need we need to know all the values possible for filtering options.

To get around this we can provide the option to not use a paginated fetch of the data (so not using the `offsetParams` to fetch data) and then just assume the view has passed in all the data available. As  a result we do not fetch all the data again. This means we would just have to provide the option to slice data or query the API again to fetch data based on offsetParams. A check maybe required before doing the slice (so the `stopIndex` is not assumed to be greater than the actual data length) and make sure the count we use is depending on if fetching data via pagination has been flagged so we can choose whether to use `totalDataCount` or the `data.length`.

**Comment by GoelBiju** [comment]
> A feature that needs to be implemented is filtering. At the moment querying for ISIS means that we cannot use the distinct option to get only the data we need, meaning all data is fetched when we need we need to know all the values possible for filtering options.
> 
> To get around this we can provide the option to not use a paginated fetch of the data (so not using the `offsetParams` to fetch data) and then just assume the view has passed in all the data available. As a result we do not fetch all the data again. This means we would just have to provide the option to slice data or query the API again to fetch data based on offsetParams. A check maybe required before doing the slice (so the `stopIndex` is not assumed to be greater than the actual data length) and make sure the count we use is depending on if fetching data via pagination has been flagged so we can choose whether to use `totalDataCount` or the `data.length`.
> 
> As @louise-davies this is a bug and once this issue has been fixed in the future we can provide the option to just provide this via pagination only. The custom view at the moment will need to pass in an array of all the data returned for the specific property (from the whole data and not just the paginated data on the page) otherwise the filtering for that property cannot be done.

Allowed both options in https://github.com/ral-facilities/datagateway/commit/c89ee8ed3edc9ae92a6f0aebba3d5e4732ce070a. We now need to provide filtering methods to put data in the state to get filtering information.

**Comment by GoelBiju** [comment]
Once the card view has been implemented, the main components need to be moved into `datagateway-common`. 

- [ ] Move components `card` and `cardView` into `datagateway-common`.

**Comment by GoelBiju** [comment]
I have removed the counting of the filtering options in https://github.com/ral-facilities/datagateway/commit/b212c35fa8683634c51c4f0c73c464763c471801. This is due to the fact that the API currently does not support fetching a single property for all data. Without this, we will have to fetch all data and then we would not require pagination. If this is added then we can add back in the count which is similar to what is mocked up by PanOSC. 

An issue has been created to track this feature (#265) so it can be added in the future.

**Comment by GoelBiju** [comment]
Mentioned by @louise-davies, there are already actions which allow for filtering i.e. `filterTable` which adds a value to the existing `Filter` object in state. We will need to add support for string and number arrays so that multiple items can be added to support filtering (using `in` for `where` in the API query).

The following needs to be done in order to adjust filtering to work using the existing state:

- [ ] add string/number array handling for `Filter` and handle that in `getApiFilter`,

- [ ] adjust `loadURLQuery` and `getURLQuery` to parse and create queries based on the `filter` in state instead of the `query.filters`,

- [ ] rename `filterTable` to `filterData` as it will support card view as well as the table,

- [ ] all card view components need to fetch count whenever the filter is updated.

- [ ] ensure that in the

**Comment by GoelBiju** [comment]
> A feature that needs to be implemented is filtering. At the moment querying for ISIS means that we cannot use the distinct option to get only the data we need, meaning all data is fetched when we need we need to know all the values possible for filtering options.
> 
> To get around this we can provide the option to not use a paginated fetch of the data (so not using the `offsetParams` to fetch data) and then just assume the view has passed in all the data available. As a result we do not fetch all the data again. This means we would just have to provide the option to slice data or query the API again to fetch data based on offsetParams. A check maybe required before doing the slice (so the `stopIndex` is not assumed to be greater than the actual data length) and make sure the count we use is depending on if fetching data via pagination has been flagged so we can choose whether to use `totalDataCount` or the `data.length`.
> 
> As @louise-davies this is a bug and once this issue has been fixed in the future we can provide the option to just provide this via pagination only. The custom view at the moment will need to pass in an array of all the data returned for the specific property (from the whole data and not just the paginated data on the page) otherwise the filtering for that property cannot be done.

As an update to this, in the future the `distinct` filter will be working for ISIS endpoints and also the issue relating to [fetching data with a nested properties](https://github.com/ral-facilities/datagateway-api/issues/122) this means we can use the distinct filter for getting filters like `INVESTIGATIONINSTRUMENT.INSTRUMENT.NAME` and then pagination will work for fetching data with nested properties with `where`.

At the moment the code to do fetching without pagination will be removed and there will be no filtering on the ISIS tables.

**Comment by GoelBiju** [comment]
There is an active issue regarding having a [feature for showing the count of the specific filter options](https://github.com/ral-facilities/datagateway/issues/265). Previously this was demonstrated by fetching the distinct filters and then counting via client-side (for a lot of data this may not be feasible).

**Comment by GoelBiju** [comment]
Add the following filters to DLS (DIAMOND) pages:

**Comment by GoelBiju** [comment]
We need to ensure that filters and sorts queries are supported by the table:

- [ ] ensure that the filters query works with table,

- [ ] ensure that sorts query parameter is supported by table.

**Comment by GoelBiju** [comment]
Tables now support filters and sorts, although switching between views keeps the same data and does not clear the data appropriately.

- [ ] Switching between views should reload the data based on the current URL queries.

**Comment by GoelBiju** [comment]
Following a code review of this branch, a couple of features and issues were noted:

- [ ] make the navigation bar (breadcrumbs and results) sticky, so that scrolling down on the card view will still show it,

- [ ] cards per page randomly disappeared after clearing a filter,

- [ ] extract out components of `CardView` to decouple it from the state e.g. advanced search, filters panel to simplify it.

**Comment by GoelBiju** [comment]
We also need to add in forward support for search and sort queries (for when they are implemented):

- [ ] add sort (with a *Sort By* box with elements); has `disableSort` option,
- [ ] add support for sort queries,
- [ ] add support for search queries.

**Comment by GoelBiju** [comment]
Adding tests to-do:

- [ ] Entity card tests,

- [ ] Card view tests,

- [ ] Generic card view tests,

- [ ] ISIS card view tests,

- [ ] DLS card view tests.

**Comment by GoelBiju** [comment]
An issue found is that after applying a custom filter the pagination component does not re-render with new values. This leads to the possibility that you can click on a page number which is incorrect and the card view would not show any data.

- [ ] Re-render pagination component when a custom filter is applied.

**Comment by GoelBiju** [comment]
Add icons support in line with the [suggested UI improvements](https://github.com/ral-facilities/datagateway/issues/341#issuecomment-664388698). Icons won't be added to title and description but will be added to the information area:

- [ ] icons are supported on information in card via the card view.

**Comment by GoelBiju** [comment]
An issue that is still persistent is that data is fetched twice from the API (due to the count updating later on?). So for all count requests we get the data being fetched twice:

- [ ] **important**: data gets fetched twice after a count request.

**Comment by GoelBiju** [comment]
> Add icons support in line with the [suggested UI improvements](https://github.com/ral-facilities/datagateway/issues/341#issuecomment-664388698). Icons won't be added to title and description but will be added to the information area:
> 
> * [x]  **important**: icons are supported on information in card via the card view.

Icons can still be changed after a sprint review.

**Comment by GoelBiju** [comment]
The initial data fetch with a max results query parameter results in the limit being calculated as -1.

- [ ] Initial data fetch does not occur with a limit of -1.

**Comment by GoelBiju** [comment]
> An issue that is still persistent is that data is fetched twice from the API (due to the count updating later on?). So for all count requests we get the data being fetched twice:
> 
> * [ ]  **important**: data gets fetched twice after a count request; we only want one count and one data request (with all changes in sort/filters/custom filters/max results).
> 
> Looking at Redux we can see that `clearData` gets called twice and fetch data is called again. Most likely due to a state update meaning useEffects are run again and the parameters still allow for another request to be made (check `loadedData`?).

Furthermore if we are navigating from a card view which already had a loaded count, then the previously used count is also fetched twice:

- [ ] Navigating between card views does not re-issue a count request from the previous card view (this is because it is still in state?)

**Comment by GoelBiju** [comment]
> An initial data fetch with a max results query parameter results in the limit being calculated as -1 and therefore the data request fails.
> 
> * [x]  **important**: Initial data fetch does not occur with a limit of -1.

The num pages and start/stop index was strictly checking for -1, this has been changed to only fetch data for greater values.

**Comment by GoelBiju** [comment]
> An issue that is still persistent is that data is fetched twice from the API (due to the count updating later on?). So for all count requests we get the data being fetched twice:
> 
> * [ ]  **important**: data gets fetched twice after a count request; we only want one count and one data request (with all changes in sort/filters/custom filters/max results).
> 
> Looking at Redux we can see that `clearData` gets called twice and fetch data is called again. Most likely due to a state update meaning useEffects are run again and the parameters still allow for another request to be made (check `loadedData`?).

This seems like it is still an issue within the CardView component. This should be investigated and we need to ensure that the CardView component does not produce duplicate requests.

**Comment by GoelBiju** [comment]
> > An issue that is still persistent is that data is fetched twice from the API (due to the count updating later on?). So for all count requests we get the data being fetched twice:
> > 
> > * [ ]   **important**: data gets fetched twice after a count request; we only want one count and one data request (with all changes in sort/filters/custom filters/max results).
> > 
> > Looking at Redux we can see that `clearData` gets called twice and fetch data is called again. Most likely due to a state update meaning useEffects are run again and the parameters still allow for another request to be made (check `loadedData`?).
> 
> Furthermore if we are navigating from a card view which already had a loaded count, then the previously used count is also fetched twice:
> 
> * [ ]  **important**: navigating between card views does not re-issue a count request from the previous card view (this is because it is still in state?)

This no longer seems to be an issue and I do not see duplicate count requests.

**Comment by GoelBiju** [comment]
> > An issue that is still persistent is that data is fetched twice from the API (due to the count updating later on?). So for all count requests we get the data being fetched twice:
> > 
> > * [ ]   **important**: data gets fetched twice after a count request; we only want one count and one data request (with all changes in sort/filters/custom filters/max results).
> > 
> > Looking at Redux we can see that `clearData` gets called twice and fetch data is called again. Most likely due to a state update meaning useEffects are run again and the parameters still allow for another request to be made (check `loadedData`?).
> 
> This seems like it is still an issue within the CardView component. This should be investigated and we need to ensure that the CardView component does not produce duplicate requests.

If this issue still exists, then it should hopefully be fixed through the refactor of using react-query for table and card views in #701.
