### ISSUE TITLE
Detail panel tab resets when scrolling

### ISSUE THREAD

**Issue by patrick-austin** [ral-facilities/datagateway#1331]
**Description**:

Expand an entity (checked it for datafiles and instruments but assume it'll happen for all entities?)
![image](https://user-images.githubusercontent.com/61705287/179259708-484620e5-d5c8-4203-8e88-d01bd2f34cb7.png)

Swap detail panel tabs
![image](https://user-images.githubusercontent.com/61705287/179259786-917cd783-9375-4098-9a63-07323c97fc4f.png)

Scroll down so the panel is out of sight
![image](https://user-images.githubusercontent.com/61705287/179259884-bdea2282-454a-4e98-8c17-b2c35d332735.png)

When scrolling back up, the tab has reset to the first but still has the height of the second. This either leeds to information being cut off as below, or loads of dead space if the second tab was taller.
![image](https://user-images.githubusercontent.com/61705287/179259926-094be06d-4f01-460b-bd8b-2d5fff94da4b.png)

**Acceptance criteria**:
- [ ] Scrolling back to an expanded details panel doesn't switch tabs (or at least the height is correct when it does?)

**Comment by louise-davies** [comment]
This is likely due to the row virtualization - if you scroll far enough away from the row that's expanded then it's unmounted (as all rows are for performance reasons). Hence when you go back it "forgets" the tab (this is local state)

**Comment by louise-davies** [comment]
There's three solutions I can conceptualise:
1. The expanded row is not virtualized and therefore not unmounted
2. We somehow store the current tab of the details panel the user is looking at, which is then passed as a prop to the details panel so it remembers it correctly
3. We set the height back to the "standard" height when the row is scrolled out of view - meaning it's fine if the tab resets as at least the layout is correct
