### ISSUE TITLE
Error loading /datagateway-dataview-settings.json: Request failed with status code 404

### ISSUE THREAD

**Issue by johnfelipe** [ral-facilities/datagateway#1368]
https://gist.github.com/fa808e461625a230e0d139fa770f64d7

:3000/datagateway-dataview-settings.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
index.tsx:160 Error loading /datagateway-dataview-settings.json: Request failed with status code 404

Pls view this video

https://drive.google.com/file/d/19Ptyy6DD3FQiPyzrbU1WFsQ2X3ngrdj0/view?usp=drivesdk

how solve this?

**Comment by MRichards99** [comment]
Hi there,

Are you from a facility that uses ICAT to store experiment metadata?

For your issue, I believe you will need a `datagateway-dataview-settings.json`. There is an example file in the repo which you can copy as a template.
