### ISSUE TITLE
Detect whether e2e test is run locally or CI and select the correct settings file accordingly

### ISSUE THREAD

**Issue by kennethnym** [ral-facilities/datagateway#1370]
**Description**:
At the moment if e2e tests are run locally they'd fail because the settings file point to URLs that only work in a CI environment. There should be a way to detect whether the tests are run in CI or locally and select the correct settings accordingly. That way we don't have to manually edit the settings file to make the tests run in environments other than CI.

**Acceptance criteria**:
- [ ] The environment is detected correctly and the correct settings file is used accordingly in e2e tests.

**Comment by louise-davies** [comment]
There's one potential problem to the solution that was implemented - the user's local settings file might have options set/not set that don't match what CI expects.
