### ISSUE TITLE
Incorrect study dates and duplicate rows appearing

### ISSUE THREAD

**Issue by sam-glendenning** [ral-facilities/datagateway#1390]
## Description:
I noticed an issue on ISIS prod whereby filtering on date parameters for studies can result in rows being displayed that show results outside the user's filtered date range.

See https://data.isis.stfc.ac.uk/browseStudyHierarchy/instrument/23/study?filters=%7B%22studyInvestigations.investigation.startDate%22%3A%7B%22endDate%22%3A%222018-08-08%22%2C%22startDate%22%3A%222017-08-08%22%7D%7D&sort=%7B%22studyInvestigations.investigation.startDate%22%3A%22desc%22%7D for an example. You will notice we are filtering on start date between 2017 and 2018 and a result has appeared for 2015.

After discussing this with @MRichards99, who was also in the room, we came to the conclusion that this study is being displayed because it contains _at least one_ investigation matching the user's query. However, instead of displaying the start date for that matching investigation, it displays the start date for the _first_ investigation in that study's list of investigations (which was 2015 in this case).

I've also ascertained that this can lead to what looks like duplicate rows appearing. Here's what happens:
1. for each investigation that matches the user's search, a row is created in the table, containing its study info
2. because of the above, _the start date of the first investigation of that study_ is inserted into the study start date field (not the study start date)
3. therefore, if a study has, for example, two investigations that match the user's search, two rows for that study will be displayed that look exactly the same. The start date will contain the start date of the _first_ investigation, ignoring the start date of the other completely

The studies view (two rows, one for each matching investigation of that study)
![image](https://user-images.githubusercontent.com/71134574/184619828-50f5c2ac-941e-4e36-a9ab-5c6baafd33db.png)

The investigation view of that study (they both have different start dates but only the first is used in the study table)
![image](https://user-images.githubusercontent.com/71134574/184619892-721093fd-4ec3-4a70-8b37-b6bbab514f8e.png)

Because these two issues are intrinsically linked, I recommend both be tackled at the same time.

## Tackling the problem:
I'd recommend starting here - https://github.com/ral-facilities/datagateway/blob/4a727092ba3badab5e0c460783f70acf903a2523/packages/datagateway-common/src/table/cellRenderers/cellContentRenderers.tsx#L38
This could be where the incorrect study info is obtained. We also need to determine what other views could be affected by this. Check if this affects facility cycle investigations and DataGateway Search.

@MRichards99 and I discussed the overall solution a bit but could be worth discussing further. Start with making sure the study start date field in the studies table is correct (so insert the start date for the matching investigation in question). Next to talk about is how to tackle the duplicate rows. Do we want this to happen, especially since both link to the same page anyway? Perhaps it is best to determine if we have two duplicate rows and only display one (perhaps the first matching one).

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by louise-davies** [comment]
I wonder if this is worth prioritising - as we'll likely want to migrate over to using `DataPublication`s instead of `Study`s now that ICAT 5 is released. I remember these were problems at the time, but there's many problems with the `Study` view due to `Study`s not containing enough of the info that's necessary which needs to be grabbed from the underlying `Investigation`(s) - to which you have the problem of "which Investigation do you get the info from?"
