### ISSUE TITLE
Issue when filtering by title

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1408]
**Description**:
When navigating experiments and then filtering by title, I seemed to have found a bug.

To reproduce:
- in DG for ISIS, browse by Experiments
- choose the GEM instrument
- in the title filter, enter 'tests'

URL: https://data.isis.stfc.ac.uk/browseStudyHierarchy/instrument/28/study?filters=%7B%22studyInvestigations.investigation.title%22%3A%7B%22value%22%3A%22tests%22%2C%22type%22%3A%22include%22%7D%7D&sort=%7B%22studyInvestigations.investigation.startDate%22%3A%22desc%22%7D

the first 3 results seem OK, but not sure why the fourth result is listed - see screenshot

<img width="1180" alt="Screenshot 2022-09-02 at 16 30 09" src="https://user-images.githubusercontent.com/1417033/188183580-93340b1e-e373-4004-bd4d-f8299444b78d.png">

Now, changing the filter from include to exclude, note that the first result contains 'tests' (and it wasn't given in the previous list)

<img width="1345" alt="Screenshot 2022-09-02 at 16 31 37" src="https://user-images.githubusercontent.com/1417033/188183790-6b5136ab-5c91-4c23-bf1b-bc4e4fe0a4cc.png">

URL: https://data.isis.stfc.ac.uk/browseStudyHierarchy/instrument/28/study?filters=%7B%22studyInvestigations.investigation.title%22%3A%7B%22value%22%3A%22tests%22%2C%22type%22%3A%22exclude%22%7D%7D&sort=%7B%22studyInvestigations.investigation.startDate%22%3A%22desc%22%7D

Could there be hidding characters that are affecting these filtering results?

**Acceptance criteria**:
- [ ] Investigate and fix filtering issue

**Comment by louise-davies** [comment]
@agbeltran we think this may be related to #1390 - which is a problem with the current implementation of the study view
