### ISSUE TITLE
Entity checkboxes are non-interactable if parent entity in cart selection

### ISSUE THREAD

**Issue by sam-glendenning** [ral-facilities/datagateway#1472]
**Description**:
When attempting to add an entity to the selection (cart), if any of its parent entities are already in the selection, the checkbox will do nothing when we try to tick it. This is due to the way the TopCAT backend handles cart items. For example, if a dataset is in the cart, so are all of its datafiles. This is by design and is not being changed.

However, confusion arises because the children of the entity in the cart do not have their checkboxes ticked, so when visiting them, the user may be confused about whether or not they are in the cart in the first place. And when attempting to interact with these checkboxes, nothing visible happens (a POST request is actually made to the backend but it doesn't modify the cart).

To fix this visual flaw, we should add some additional logic to the checkboxes. We need to verify if any of the entity's parents (and any of its parents, and so on) are currently in the cart. If so, the checkboxes should be ticked and greyed out to prevent user interaction (since nothing happens if they are interacted with anyway). To try and provide transparency, we should also add a tooltip over the checkbox to explain that it can't be interacted with while one of its parent entities is in the cart (we can work on the wording of this). 

Similar logic should also be done in card view (and as such, the add to cart button should say "remove from cart", be greyed out and have a tooltip in the same scenario).

This issue is only present on Diamond. ISIS's backend process each checkbox tick as a separate add to cart action, meaning an entity can be downloaded alongside its parent entity as well.

[Video.webm](https://user-images.githubusercontent.com/71134574/203378113-c7b2e84c-128d-4965-97dd-7f6f6b8e142f.webm)

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by louise-davies** [comment]
Just a note: the issue is indeed present on ISIS as well - the difference maybe Sam was referring to was that in ISIS you can download individual files not via the cart, but if you try to check a datafile where the parent dataset is already in the cart it does not check them like in Sam's clip
