### ISSUE TITLE
React error #185 when opening details panel on DLSVisitsTable and DLSDatasetsTable

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#313]
**Description**:
When opening the details panels on the DLS (DIAMOND) visits and datasets table a React error occurs. Specifically, this due to the number of updates occurring as stated by the full error message stated in the [React documentation](https://reactjs.org/docs/error-decoder.html?invariant=185).

**Acceptance criteria**:
- [ ] Opening the details panel for DLS (DIAMOND) visits and datasets table does not cause an error.

**Comment by louise-davies** [comment]
I cannot recreate this issue locally, and it doesn't occur on preprod

**Comment by GoelBiju** [comment]
@louise-davies has tried to reproduce this same issue on her development environment but is unable to do so. I will try to clone a new repository and set up and see if this occurs. This issue looks like it might be caused due to the detailsPanelResize but why it is occurring specifically on one setup and not the other is still trying to be worked out.

**Comment by GoelBiju** [comment]
> @louise-davies has tried to reproduce this same issue on her development environment but is unable to do so. I will try to clone a new repository and set up and see if this occurs. This issue looks like it might be caused due to the detailsPanelResize but why it is occurring specifically on one setup and not the other is still trying to be worked out.

This issue seems to occur on a new set up repository but at the moment cannot be reproduced except for my computer.

**Comment by GoelBiju** [comment]
@louise-davies this issue is occurring on the DLS My Data table as well but not for the ISIS one.

**Comment by louise-davies** [comment]
On a fresh clone of master on my machine, I cannot recreate these errors. I tried all of the DLS visit, dataset and my data tables, I tried on both my smaller laptop screen, my larger monitor, and even did a test on an emulated "mobile size" browser.

**Comment by GoelBiju** [comment]
> On a fresh clone of master on my machine, I cannot recreate these errors. I tried all of the DLS visit, dataset and my data tables, I tried on both my smaller laptop screen, my larger monitor, and even did a test on an emulated "mobile size" browser.

@louise-davies I'll close this issue since it cannot be reproduced.

**Comment by louise-davies** [comment]
It seems as this occurs on ISIS tables as well - could you (@tswinb) describe the current conditions you are able to use to reproduce the error? So I can help with investigation of the issue + for future reference

**Comment by tswinb** [comment]
@louise-davies This issue occurred for me when running Cypress tests in interactive mode: Electron 80, Cypress 4.11.0
Specifically running isis datafiles.spec.ts at the points where it clicks on 'Show details' at
http://localhost:3000/browse/instrument/1/facilityCycle/14/investigation/87/dataset/118/datafile 
But, it occurs on all datafiles and within (as far as I can tell) all datasets within the ISIS tables.

I've only been able to reproduce the error in this specific circumstance, and have even had times when it doesn't occur: The first time I ran the tests this morning on both Electron 80 and Edge 84, the error didn't occur, but as soon as I restarted Cypress it occurs consistently.
