### ISSUE TITLE
Data search feature

### ISSUE THREAD

**Issue by esl-lewis** [ral-facilities/datagateway#33]
Description:
Develop a data search function with the ability to search between given start and end dates, and filter by investigation, dataset and datafile (ISIS) and visit and dataset (Diamond).

Acceptance criteria:

Functioning UI

- URL updates when filters and dates are applied
- Apply correct filter options for both ISIS and Diamond
- Correct data is retrieved
- Data is added to 'cart' and available for download

**Comment by GoelBiju** [comment]
@tswinb I have added the code to datagateway-search to allow theme option messages sent from the parent application to be received and then passed to the `MuiThemeProvider` which wraps around the search components.

**Comment by GoelBiju** [comment]
As mentioned to @louise-davies , @tswinb there seems to be an issue with the data loading when running the search branch on the SciGateway parent application.

**Comment by GoelBiju** [comment]
> @tswinb I have added the code to datagateway-search to allow theme option messages sent from the parent application to be received and then passed to the `MuiThemeProvider` which wraps around the search components.
> 
> The tests will need to be added to the search feature pull request #112.
> 
> * [ ]  Add test for inheriting themes from a parent application for datagateway-search.

Once #99 has been merged into master, there will be no need to add any further code/test to inherit theme options.

**Comment by GoelBiju** [comment]
> > @tswinb I have added the code to datagateway-search to allow theme option messages sent from the parent application to be received and then passed to the `MuiThemeProvider` which wraps around the search components.
> > The tests will need to be added to the search feature pull request #112.
> > 
> > * [ ]   Add test for inheriting themes from a parent application for datagateway-search.
> 
> Once #99 has been merged into master, there will be no need to add any further code/test to inherit theme options.

The master branch has now been merged in and the `App` component has been updated to use `DGThemeProvider`.
