### ISSUE TITLE
UI improvements for table: icons

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#341]
**Description**:
Add improvements to the user interface for the table. The first improvement suggested by @agbeltran is to add appropriate matching icons for the columns in the `Table`. There are some various sources to take note of i.e. [SciCat](https://scicatproject.github.io/).

**Acceptance criteria**:
- [x] Add relevant icons to columns/fields in the table to correspond with data.

**Comment by agbeltran** [comment]
Thanks @GoelBiju for raising the issue. We discussed that we are going to use [Material UI icons](https://material-ui.com/components/material-icons/).

We want to be consistent and use the same icons for the same labels across the application.

For initial discussion (let's complete the list collaboratively):
|   |   |
|---|---|
|  title |  TitleIcon |
|  description |  DescriptionIcon |
| identifier (e.g. DOI)  |   |
| date  | CalendarToday  |
|   |   |
|   |   |

**Comment by GoelBiju** [comment]
I have removed CardView from this as we can add that in to the card view branch.
