### ISSUE TITLE
UI improvement: add pagination at the top too

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#395]
**Description**:
Currently, pagination is only available at the bottom of the page. It would be helpful to add it at the top as well in the card view (below the search box). See screenshot.

<img width="1721" alt="Screenshot 2020-09-02 at 09 13 28" src="https://user-images.githubusercontent.com/1417033/91956730-03a13900-ecfd-11ea-8bc7-b536fcbd3b9d.png">

**Acceptance criteria**:
- [x] Pagination added below the search box in card view

**Comment by GoelBiju** [comment]
@agbeltran I had seen this issue and decided to work on it before I saw it was assigned to @tswinb. I have quickly addressed in this commit and allowed for a `paginationPosition` prop to passed to card view which allows `top` or `bottom` to be specified depending on where you would like the pagination to appear.

Maybe it might not be what you wanted, it looks like this:

![image](https://user-images.githubusercontent.com/16869075/92252375-0c913680-eec6-11ea-8d9f-db7efc5dc4e3.png)

**Comment by GoelBiju** [comment]
@agbeltran , @tswinb mentioned if you wanted it in both places at once. If so a "both" option can maybe be provided as well?

**Comment by agbeltran** [comment]
thanks a lot @GoelBiju for working on this! Yes, I think it would be best to provide it on both places (top and bottom) and if there are many datasets, it takes a while to scroll up and down. So the 'both' option will be good. @tswinb perhaps something you can look at?
