### ISSUE TITLE
UI improvement: add download cart at top of table/card view

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#415]
**Description**:
Currently the download cart is shown as separate plugin; add links in table/card view to the download cart view.

**Acceptance criteria**:
- [ ] Add link to download cart at the top of DataGateway table/card view (next to results)
- [ ] Add count of items in download cart

**Comment by louise-davies** [comment]
This would probably best be located next to the "Results: X" part of the UI, but I am open to ideas
