### ISSUE TITLE
Add loading indicator to tables

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#426]
**Description**:
Currently, there is no loading indicator on the tables, so users don't know if there is data attempting to be loaded or if there is just no data.

**Acceptance criteria**:
- [ ] A loading indicator is added to the table

**Comment by GoelBiju** [comment]
@louise-davies just as a comment to this, there is a [loading indicator](https://github.com/ral-facilities/datagateway/blob/feature/create-card-view-%23128/packages/datagateway-dataview/src/page/pageContainer.component.tsx#L279-L291) on the `PageContainer` (on the card-view branch) which uses a `LinearProgress` component to be shown when data is being loaded when cards are toggled. Not sure if a similar approach should be used for tables (if that is what you had in mind).
