### ISSUE TITLE
Chrome requests sometimes infinitely "pending"

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#427]
**Description**:
@kevinphippsstfc has observed chrome requests to `datagateway-api` sometimes never load and are in a "pending" state infinitely. This may just be an issue with `datagateway-api` or might be how we're interacting with it.

**Acceptance criteria**:
- [ ] Investigate the chrome pending issue and ensure it no longer occurs

**Comment by agbeltran** [comment]
@stfc-lam will test again in Chrome, but from general discussion in the team, it doesn't seem to be happening anymore

**Comment by stfc-lam** [comment]
Have tested both datagateway-dev.isis.stfc.ac.uk  and datagateway-preprod.diamond.ac.uk  and cannot replicate this bug.

**Comment by GoelBiju** [comment]
@louise-davies should this issue be closed since it has been archived already?

**Comment by louise-davies** [comment]
This hasn't occured in a long time
