### ISSUE TITLE
In dark mode, dark blue text on the black or dark grey background is unreadable

### ISSUE THREAD

**Issue by kevinphippsstfc** [ral-facilities/datagateway#428]
**Description**:
So far I have noticed this in a couple of places. When you click into the "Search Data" box and on the sign in box when you change from one authenticator to another.

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by patrick-austin** [comment]
Places in DG plugins with dark blue text/highlight while in darkmode:
- Search bar border/default text on focus (dataview)
- Underscore effect for all table input fields on focus (all plugins)
- Default text/border for input fields in search box (search)
- Default text for search results panel (search)

Other places (e.g. checkboxes) use a lighter blue, will try to set the above places to use this too.
Buttons/tab selectors use white text on dark blue (on dark background) but this should be OK so won't change those places.
Created ral-facilities/scigateway#438 for the places where this happens there (login screen, cookie page).
