### ISSUE TITLE
What does Toggle Cards do?

### ISSUE THREAD

**Issue by kevinphippsstfc** [ral-facilities/datagateway#429]
**Description**:
It's not clear to me from its name and it is not on the help tour. I'm at the top level of the DataGateway Table - ISIS view and if I turn it on now the 14 results in the table disappear (it still says Results:14 in the top corner but the table is blank).

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by agbeltran** [comment]
We discussed with @louise-davies about changing the label to "Display as Card"

**Comment by patrick-austin** [comment]
The toggle has a step in the help tour and the label has been changed, so closing this issue.
