### ISSUE TITLE
Extend tour

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#430]
**Description**:
The first pass of the tour was done some time ago and does not include the latest features. The tour needs to be extended to provide guidance on the features not yet covered (e.g. #429). 

**Acceptance criteria**:
- [ ] Tour extended to include all the new features

**Comment by patrick-austin** [comment]
The tour was extended, and the functionality to add more steps is in place. The text may need reviewing or new steps adding as features are added, but unless there's anything that currently needs adding I'm closing this issue.
