### ISSUE TITLE
Network Error messages due to self-signed certificate

### ISSUE THREAD

**Issue by kevinphippsstfc** [ral-facilities/datagateway#432]
**Description**:
Can we put a genuine certificate on the ICAT to prevent these messages? Having to go to a separate URL and accept the certificate to prevent these messages is too much of a workaround for users trying to test it, and the error messages give a negative first impression.

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by louise-davies** [comment]
A certificate was requested for scigateway-preprod.esc.rl.ac.uk and has been added to ICAT so these messages should no longer occur
