### ISSUE TITLE
Sample ISIS and Diamond data required on preprod

### ISSUE THREAD

**Issue by kevinphippsstfc** [ral-facilities/datagateway#433]
**Description**:
Can we link the preprod server up to the preprod Diamond and ISIS ICATs? I think this is going to be essential both for testing of the actual size and shape of real facility data (thousands of datasets, millions of files) but also to help ISIS and Diamond users see data they are familiar with in the new UI. Personally, I find it difficult to test with the fake data.

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by louise-davies** [comment]
DLS and ISIS preprod machines have been set up which point to ICATs. However, due to waiting on icat.server 4.11.1 upgrades, DLS data requests fail, so preprod points to Stuart's anonymised data instead.

**Comment by louise-davies** [comment]
This has been done for a while
