### ISSUE TITLE
Detailed view for a Dataset

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#473]
**Description**:
We have a [user story](https://github.com/ral-facilities/datagateway-userstories/issues/85) to include a page with a detailed view for a Dataset, including all the relevant metadata about the dataset.

For datasets with persistent identfiers/DOIs, this detailed view of the dataset equates to the dataset landing page. For that reason, we will need to have custom pages for each facility (potentially including their logos).

**Acceptance criteria**:
- [ ] Addition of page with dataset metadata

**Comment by patrick-austin** [comment]
I've had a think about how we might go about doing this, and mocked it up in the attached Powerpoint. More specifically:

- If we replace the existing link from dataset to datafile with a link to the landing page, how can we link to the datafiles from the table/card view (alternatively if we keep the existing title/name link pointing to the datafiles, then where to put the link to the landing page)
- Layout of the landing/DOI page
- How to navigate to the datafiles/child entities from the landing page
- How to navigate up to the parent entity from the landing page

I mainly refer to this being for a dataset, but ideally this would be easy to extend to investigations or other entities. That might affect the fields present on the page though.

I can think of a few ways of going about these points, so if there are any strong feelings on what looks better then I'd appreciate comments @agbeltran @louise-davies and anyone else who it'd be good to get an opinion from.

[DOI landing mocks.pptx](https://github.com/ral-facilities/datagateway/files/5546659/DOI.landing.mocks.pptx)

**Comment by agbeltran** [comment]
Many thanks for this @patrick-austin ! It looks great. I will organise a meeting to discuss the details.

**Comment by patrick-austin** [comment]
Updating with current landing pages from #547 

<img width="960" alt="study landing page" src="https://user-images.githubusercontent.com/61705287/106604351-6d956700-6557-11eb-8a47-7bb4f3e86390.png">
<img width="960" alt="investigation landing page" src="https://user-images.githubusercontent.com/61705287/106604344-6b330d00-6557-11eb-9f3a-8aa1e98c2fb9.png">
<img width="960" alt="dataset landing page" src="https://user-images.githubusercontent.com/61705287/106604355-6ec69400-6557-11eb-8611-532cba5a52db.png">
