### ISSUE TITLE
[datagateway-download] Create "download status" view

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#48]
This is a large issue that may get split up into smaller issues.

Recreate the TopCAT download status view. Unlike TopCAT which has it as a modal, we should instead have it as a separate page accessed via the menu (Data/Download). I think we shall need two "tabs" - one for the download cart and one for the download status page.

Download status page mockup (based on current TopCAT):
![downloads](https://user-images.githubusercontent.com/22525471/66578069-56688400-eb72-11e9-9a45-41a778238531.png)

Acceptance criteria:
- [x] Have a download status view that displays the carts the user has requested for download, and their statuses
- [x] The user can download individual carts
- [x] The user can delete individual carts

**Comment by GoelBiju** [comment]
A basic table which retrieves the download information is present, however we still need the following:

- [ ] Date filter working for the requested date (createdAt) column,
- [ ] Action buttons with API functionality to download and remove downloads.

**Comment by GoelBiju** [comment]
An additional change made is to add a prop to adjust the width of the action column.

**Comment by GoelBiju** [comment]
> Some additional changes and considerations to be made:
> 
> * [x]  add a prop to adjust the width of the action column,
> * [x]  prevent showing the download action button in the event that the download/transport type is not HTTP.

@louise-davies at the moment we can disable a download button (greyed out) if the transport type is not "https". This is more convenient as if we were to not render the button or not include the action in the actions prop passed to the table, then we encounter styling issues and will need to fix alignment of the buttons.

I have a tooltip to the disabled button where it will show why it has disabled.

**Comment by GoelBiju** [comment]
A small UI issue that has arisen is that of when plugging in the datagateway-download into the SciGateway parent application, the tab UI animation fails to update it's position. There is a [specific issue](https://github.com/mui-org/material-ui/issues/9337) mentioned on the material-ui GitHub repository for this.

We need to ensure the `updateIndicator` is called when the sidebar is opened/closed so that the correct tab is underlined.

**Comment by GoelBiju** [comment]
An addition to the table, mentioned by @agbeltran, is to have a last checked time being displayed on top of the download status table along with the refresh button. Adding the refresh button means we will have to provide the functionality that the tab or the table will be refreshed. 

- [ ] Add last checked time information on top of the download status table along with a refresh button.

**Comment by GoelBiju** [comment]
> A small UI issue that has arisen is that of when plugging in the datagateway-download into the SciGateway parent application, the tab UI animation fails to update it's position. There is a [specific issue](https://github.com/mui-org/material-ui/issues/9337) mentioned on the material-ui GitHub repository for this.
> 
> * ~[ ] Ensure the `updateIndicator` is called when the sidebar is opened/closed so that the correct tab is underlined.~

At the moment using `updateIndicator` does not seem to provide a solution to this issue. Instead we dispatch a delayed resize event in https://github.com/ral-facilities/datagateway/commit/efe88c41559933730738fdd349310f56b284133f (as mentioned in the [material-ui issue](https://github.com/mui-org/material-ui/issues/9337#issuecomment-413789329)), with a delay of 125ms so to resize after the navigation drawer closing animation in SciGateway.

The only caveat with this is that at the moment, the currently selected tab will revert to the initial cart tab with the render. A proposed way to get around this is by keeping track of the tab the user was using in sessionStorage/localStorage and then apply them after the re-size.

**Comment by GoelBiju** [comment]
Adding in the ability to store the selected tab in sessionStorage (https://github.com/ral-facilities/datagateway/commit/3a5d42d742ecade4bacf8d234d834357d54193fd) has meant that we no longer need to call the re-size event to update the tab indicator as the state is updated.

**Comment by GoelBiju** [comment]
> A basic table which retrieves the download information is present, however we still need the following:
> 
> * [ ]  Date filter working for the requested date (createdAt) column,
> * [x]  Action buttons with API functionality to download and remove download items within the table,
> * [ ]  Add in appropriate unit and e2e tests.

In addition to these, in order to complete the changes:

- [ ] Move all download related API calls to one file,

- [ ] Fix table column sorting, so that the user does not have to click multiple times to get it to work,

- [ ] The filtering with the availability column does not match what is shown in the table but rather filters via what it receives internally via the API,

- [ ] Ensure "http" and "https" are handled in the DownloadStatusTable.

**Comment by GoelBiju** [comment]
An additional consideration is to ensure the UI is not blocked when fetching data in either tabs (download-cart/download-status). It is very much possible that if there is a lot of data to be fetched, the UI/animation for switching tabs can freeze as the data is loaded first.

**Comment by GoelBiju** [comment]
> > A basic table which retrieves the download information is present, however we still need the following:
> > 
> > * [x]   Date filter working for the requested date (createdAt) column,
> > * [x]   Action buttons with API functionality to download and remove download items within the table,
> > * [ ]   Add and update appropriate unit and e2e tests.
> 
> In addition to these, in order to complete this issue:
> 
> * [x]  Move all download related API calls to one file,
> * [x]  ~Fix table column sorting, so that the user does not have to click multiple times to get it to work.~ This was it moving through the various states: ascending, descending and back to the original list,
> * [ ]  The filtering with the availability column does not match what is shown in the table but rather filters via what it receives internally via the API,
> * [x]  Ensure "http" and "https" are handled in the DownloadStatusTable.

A possible solution to the filtering of the availability column is to implement a custom text filter (as suggested by @louise-davies). This approach could be taken or in turn we could just show to current status of downloads but as camel-case, ensuring the filtering works.

**Comment by GoelBiju** [comment]
It is worth mentioning that the cypress-example-recipes repository contains some [examples](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__tab-handling-links/cypress/integration/tab_handling_anchor_links_spec.js) on how to test links that open a new page. Suitable for when we click on a download which opens a new page.

**Comment by GoelBiju** [comment]
> > A small UI issue that has arisen is that of when plugging in the datagateway-download into the SciGateway parent application, the tab UI animation fails to update it's position. There is a [specific issue](https://github.com/mui-org/material-ui/issues/9337) mentioned on the material-ui GitHub repository for this.
> > 
> > * ~[ ] Ensure the `updateIndicator` is called when the sidebar is opened/closed so that the correct tab is underlined.~
> 
> At the moment using `updateIndicator` does not seem to provide a solution to this issue. Instead we dispatch a delayed resize event in [efe88c4](https://github.com/ral-facilities/datagateway/commit/efe88c41559933730738fdd349310f56b284133f) (as mentioned in the [material-ui issue](https://github.com/mui-org/material-ui/issues/9337#issuecomment-413789329)), with a delay of 125ms so to resize after the navigation drawer closing animation in SciGateway.
> 
> The only caveat with this is that the currently selected tab will revert to the initial cart tab with each re-render. A proposed way to get around this is by keeping track of the tab the user was using in sessionStorage and then selecting that tab before/after the re-size event.
> 
> * [x]  Store the current tab in session and apply before/after a re-size event.

To follow up on this issue, it seems to have a solution through https://github.com/mui-org/material-ui/pull/27791. It might be worth looking into this further in another issue and remove the need to store the current tab in sessionStorage and call the resize event @louise-davies?
