### ISSUE TITLE
Display banner to users that they need to login in my data view

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#481]
**Description**:
Due to the autologin functionality, one of the only reasons for users to login may be the My Data view. However, if a user navigated to this whilst logged in anonymously they will have no data, which may cause confusion if they forget they haven't logged in. The My Data pages should thus detect if a user is autologged in/logged in anonymously, and display a message to remind the user that they will need to login to see their own data.

Autologin code is in SciGateway and it would be best to take a look there to see how the process is handled before tackling this issue.

**Acceptance criteria**:
- [ ] Message of some sort is displayed to the user if they attempt to look at My Data whilst logged in automatically/as anon

**Comment by agbeltran** [comment]
Hi @louise-davies - this sounds like a good solution, but I wonder if another option is to disable the 'My Data' option in the menu altogether?

**Comment by louise-davies** [comment]
@agbeltran This solution was proposed by Sonia iirc. Disabling 'My Data' should be possible - it would require API additions in SciGateway to support it of course - but it would still not solve the underlying issue of users wondering why they can't access their data (unless you would also include a hover tooltip or something to similarly tell the users to login).
