### ISSUE TITLE
Add exclude text filter

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#484]
**Description**:
Sylvie mentioned that an exclusive text filter would be useful for users in Diamond. In and of itself this should be simple, but then some functionality to be able to select between the inclusive and exclusive filters would be needed. This could then be extended in the future to other types of text filters.

**Acceptance criteria**:
- [ ] Users can filter by exclusive text (e.g. title NOT containing "dog")
- [ ] Users can switch between different text filter types.

**Comment by agbeltran** [comment]
@MRichards99 to check if NOT like could be done already
