### ISSUE TITLE
[datagateway-download] Create download confirmation view

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#49]
This is a large issue that may get split up into smaller issues.

Recreate the TopCAT download confirmation view. This is accessed when the user clicks download on the cart page, and they should be redirected to this page.

Download confirmation mockup (based on current TopCAT):
![confirm download](https://user-images.githubusercontent.com/22525471/66577611-9c711800-eb71-11e9-97d2-3e8e4a2f75a6.png)

Acceptance Criteria:
- [x] Allows the user to rename their download cart
- [x] Allows the user to select the download type
- [x] If the user cancels it sends them back to the cart view
- [x] If the user downloads then it should submit the download request
- [x] Users can supply their email and they will be emailed once their download has finished

**Comment by GoelBiju** [comment]
The download confirmation page has now been designed as modal dialog which opens up a confirmation form on the cart table view. Upon submitting a user will be conveyed the information they have submitted and link to the download status page.

**Comment by GoelBiju** [comment]
I have updated this branch to correctly now download the appropriate file immediately if the access method is http/https. The tests now remain to be completed including e2e tests and once this has been completed, a function to move from the modal dialog to the status tab page needs to be provided. This tab functionality is on #48 and will need that to be completed, so it can be incorporated once merged into master.

- [ ] Ensure the "View my downloads" link moves the user to the status tab page on #48 .

**Comment by agbeltran** [comment]
Additional requirements:
- [ ] Show the estimated download time only if IDS call return isTwoLevel = false.
- [ ] Show the estimated download time as a table with each for the potential connections speeds.

**Comment by agbeltran** [comment]
- [ ] For confirmation text, use "Successfully submitted download request."  in all the cases.

**Comment by GoelBiju** [comment]
@agbeltran I have added in the additional requirements in the latter commits.

**Comment by GoelBiju** [comment]
To note out the specific tests that are needed for code coverage in DownloadConfirmationDialog component:

- [ ] "null" check within DialogTitle component - [L71](https://github.com/ral-facilities/datagateway/blob/feature/download-confirmation-%2349/packages/datagateway-download/src/downloadConfirmation/downloadConfirmDialog.component.tsx#L71)

- [ ] Varying the estimated download times in the table to ensure that all cases for the code is handled, i.e. test with times which result in days, hours, minutes and seconds - [L179-184](https://github.com/ral-facilities/datagateway/blob/feature/download-confirmation-%2349/packages/datagateway-download/src/downloadConfirmation/downloadConfirmDialog.component.tsx#L179-L184)

- [ ] Test to prevent download of a "prepared cart" if the status of the download is not "COMPLETE" - [L219](https://github.com/ral-facilities/datagateway/blob/feature/download-confirmation-%2349/packages/datagateway-download/src/downloadConfirmation/downloadConfirmDialog.component.tsx#L219)

- [ ] Set download name after altering input [L265](https://github.com/ral-facilities/datagateway/blob/feature/download-confirmation-%2349/packages/datagateway-download/src/downloadConfirmation/downloadConfirmDialog.component.tsx#L265)

**Comment by GoelBiju** [comment]
With this branch, there are some alterations made to the downloadCartApi and tests need to be updated:

- [ ] getIsTwoLevel

- [ ] submitCart

- [ ] getDownload

- [ ] downloadPreparedCart

**Comment by GoelBiju** [comment]
An extra item to add to the pull request is to ensure that the deleteTestDownload works on a linux environment (i.e. Ubuntu) so that we know where the file will be saved to during e2e tests are also where to delete it from.

**Comment by GoelBiju** [comment]
It is worth noting that the test altered in https://github.com/ral-facilities/datagateway/commit/f119f81631113f76455acba1a160c59b32001b7a tests that the onClose callback function has been called. This, however, does not seem to update the wrapper, meaning that the download confirmation dialog is still present. 

This could possibly be due to the fact that the Dialog is not wrapped around anything else.

**Comment by GoelBiju** [comment]
As @louise-davies mentioned on [this comment](https://github.com/ral-facilities/datagateway/pull/103#issuecomment-579727650), the  cart needs to be refreshed and updated with the latest items once the download submission has been successful.

- [ ] Refresh the Download Cart Table once the download submission has been successful.

**Comment by GoelBiju** [comment]
The function to clear the cart once the download confirmation dialog has been closed has been added in https://github.com/ral-facilities/datagateway/commit/9076ffdf808dda2affc602689cba5a1c0c5ee897.
