### ISSUE TITLE
[datagateway-table] Show total number of entities matching the criteria above the table

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#52]
TopCAT displays the total count of the number of results above the table. This should be relatively straight forward after #20 goes in, as it already fetches the total entity count.

Acceptance criteria:
- [x] Total entity count visible to the user

**Comment by GoelBiju** [comment]
I need to ensure the breadcrumb and the results count can both share the space on top of the table. I have added the results within a Material-UI Grid to test it out.

**Comment by GoelBiju** [comment]
I will test this out, along with the Material UI grid layout, on the breadcrumbs branch in order to see what kind of layout is required in order them to both fit on top of the table.

**Comment by GoelBiju** [comment]
I have added the relevant unit and e2e test for this branch, however, this still needs the breadcrumbs component to be reviewed and merged in.

**Comment by GoelBiju** [comment]
I have deleted the old branch (table-entities-count-#52) since it had code from testing with the breadcrumbs. I have created a new branch (entites-count-#52) with only the relevant code to this branch.
