### ISSUE TITLE
Configure links in search plugin to match facility

### ISSUE THREAD

**Issue by patrick-austin** [ral-facilities/datagateway#566]
**Description**:
Currently, links in the search table(s) link to `/browse/investigation/...`, the "generic" format for the entity hierarchy. For ISIS, DLS or other users with a different hierarchy, we'd want to be able to link to their respective url.

**Acceptance criteria**:
- [ ] Links in search can be made to point to the right hierarchy

**Comment by louise-davies** [comment]
This problem was only fixed for `investigations` - a similar fix needs to be made for `datasets` and `datafiles`
