### ISSUE TITLE
Replace old use of icat:token with scigateway:token

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#649]
https://github.com/ral-facilities/datagateway/blob/5d26c7d3593e987dd45605b89f5872e8cfe87c1f/packages/datagateway-download/src/downloadStatus/downloadStatusTable.component.tsx#L227

Just found this when looking into IDS calls for Kevin. Additionally, I'd say we should refactor the whole `getDataUrl` to live alongside all the other API calls in `downloadApi.ts`, and perhaps refactor `downloadPreparedCart` to use the `getDataUrl` function to reduce code duplication.

**Comment by sam-glendenning** [comment]
@louise-davies the problem with getDataUrl is that it makes use of DownloadSettingsContext (which is already used extensively in downloadStatusTable and not at all in downloadApi) which is read using React.useContext (the React library isn't imported in downloadApi either). As getDataUrl is used once in downloadStatusTable in sortedAndFilteredData, I'd argue it makes sense to keep it in there.

**Comment by louise-davies** [comment]
@sam-glendenning It only requires the `idsUrl` being passed to it - which most functions in `downloadApi.ts` do. The only reason it uses `settings` is to get the `idsUrl` and this can be refactored to be passed to it. I just think this function is highly likely to be forgotten about again because it's accessing APIs but not with the rest of the API functions
