### ISSUE TITLE
Search page - descriptive text and enable enter

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#689]
**Description**:
The Search page includes a text in the bottom part indicating "Fill out form to the left and then click search." I suggest to remove this explanation as the search box should be self-explanatory. 
In addition, currently the 'Search' button needs to be click to start the search. We should also enable clicking 'enter' in the keyboard to produce the same result

**Acceptance criteria**:
- [x] Remove descriptive text
- [x] Enable starting the search by pressing 'enter' in addition to clicking the 'Search' button

**Comment by sam-glendenning** [comment]
For future Sam so he doesn't forget - consult here: https://stackoverflow.com/questions/58699898/submit-a-form-using-enter-key-with-material-ui-core-button-in-react-js
