### ISSUE TITLE
Centre the search-box and search-table containers

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#693]
**Description**:
The search-box and search-table (results) container are left justified. I think they will look better if centred. 

**Acceptance criteria**:
- [x] show search-box and search-table containers in the centre of the page

<img width="1770" alt="Screenshot 2021-05-18 at 12 24 36" src="https://user-images.githubusercontent.com/1417033/118643355-5d3a8c80-b7d4-11eb-9fcd-ae7d52b0fb76.png">

**Comment by louise-davies** [comment]
table should span the page

**Comment by louise-davies** [comment]
ensure that placeholder text is removed

**Comment by GoelBiju** [comment]
> ensure that placeholder text is removed

The placeholder text is removed by #761 and I will test it together by merging the changes into #774.
