### ISSUE TITLE
Show label for investigations.details.visitId

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#705]
**Description**:
Currently variable instead of label showing, reported by Franz
![visitid](https://user-images.githubusercontent.com/1417033/119837144-38dc5f80-befa-11eb-9333-7bcf0ac359df.png)

**Acceptance criteria**:
- [ ] show label instead of variable

**Comment by GoelBiju** [comment]
@agbeltran is this issue the same as #743?

**Comment by louise-davies** [comment]
I still need to fix the deployment on ISIS so close once I have fixed that

**Comment by louise-davies** [comment]
This fix is now deployed on all machines
