### ISSUE TITLE
Request error when sorting DOI column

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#714]
**Description**:
Here the steps to reproduce - in DG for ISIS prod, browse to NIMORD, cycle_17_1, and in the list of investigatations sort the DOI column. 

https://datagateway.isis.stfc.ac.uk/browse/instrument/2/facilityCycle/84762458/investigation

https://datagateway.isis.stfc.ac.uk/browse/instrument/2/facilityCycle/84762458/investigation?sort=%7B%22studyInvestigations.study.pid%22%3A%22asc%22%7D

Getting 400 (bad request) for https://datagateway.isis.stfc.ac.uk/datagateway-api/instruments/2/facilitycycles/84762458/investigations?order="studyInvestigations.study.pid asc","id asc"&skip=0&limit=50&include=[{"investigationInstruments":"instrument"},{"studyInvestigations":"study"}]

**Acceptance criteria**:
- [ ] Fix request error

**Comment by MRichards99** [comment]
I had to separate the two order strings to get the request to 400, but the request to the API gives the following error message:
`Cannot use one to many relationship in 'studyInvestigations.study.pid' to order Investigation.`

This comes from Python ICAT when the `studyInvestigation.study.pid` order filter is applied to the query. This is the same behaviour as discussed in #460

**Comment by MRichards99** [comment]
This issue has been logged on Python ICAT's repo: icatproject/python-icat#83

**Comment by GoelBiju** [comment]
The merge of https://github.com/ral-facilities/datagateway-api/pull/240 should allow for this issue to be fixed once everything has been deployed again as @MRichards99 has mentioned.

**Comment by GoelBiju** [comment]
> As the DataGateway API PR as been merged, could this be closed as the issue has been fixed? Same question for #460 too

Sure, I'll close this issue and take a review of #460 to see if there is anything outstanding on that issue.
