### ISSUE TITLE
Change toggle button to a button with different labels "Display as cards" / "Display as table"

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#718]
**Description**:
Currently, it seems that the default label is "Toggle cards" which we agreed that is not the best phrasing. We agreed on changing it to a button whose label will change between "Displays as cards" and "Display as table". 

**Acceptance criteria**:
- [x] Change toggle button for cards/table view

**Comment by GoelBiju** [comment]
@agbeltran @louise-davies @sam-glendenning @MRichards99 I have changed the design of the toggle switch to be a button instead. This is what it looks like presently: 

* "Display as tables":
![image](https://user-images.githubusercontent.com/16869075/126577572-7e076461-33e6-4ceb-9c7e-c444a5383192.png)


* "Display as cards":
![image](https://user-images.githubusercontent.com/16869075/126577558-d7252446-30f6-4d1c-aa06-de79e4dcba23.png)

A few questions about the design might need to be discussed:

- The colour of the button?
- Does the button shape and look appropriate?
- Are the icons on the button appropriate?
- Where should the placement of the button be? (Should it remain in the same place as the toggle?)

**Comment by GoelBiju** [comment]
> @agbeltran @louise-davies @sam-glendenning @MRichards99 I have changed the design of the toggle switch to be a button instead. This is what it looks like presently:
> 
> * "Display as tables":
>   ![image](https://user-images.githubusercontent.com/16869075/126577572-7e076461-33e6-4ceb-9c7e-c444a5383192.png)
> * "Display as cards":
>   ![image](https://user-images.githubusercontent.com/16869075/126577558-d7252446-30f6-4d1c-aa06-de79e4dcba23.png)
> 
> A few questions about the design might need to be discussed:
> 
> * The colour of the button?
> * Does the button shape and look appropriate?
> * Are the icons on the button appropriate?
> * Where should the placement of the button be? (Should it remain in the same place as the toggle?)

Just continuing with this design for now and adding some small padding produces a view like this: 

![image](https://user-images.githubusercontent.com/16869075/127486738-c3bd25bd-7f8c-45dc-8b1b-24d09ef16d8a.png)

The other idea suggested by @louise-davies was to have the icon and the label separate. Possibly with the label to the left of a separate icon which you can click.

**Comment by sam-glendenning** [comment]
I've forgotten some of the suggestions from the last sprint review but was the length of the button/label an issue we raised? If so, could change the label to say "Card view" / "Table view"

Saying that I don't mind the look of the above screenshot! Worth presenting once again at the next sprint review for everyone's thoughts on the new design

**Comment by GoelBiju** [comment]
> I've forgotten some of the suggestions from the last sprint review but was the length of the button/label an issue we raised? If so, could change the label to say "Card view" / "Table view"
> 
> Saying that I don't mind the look of the above screenshot! Worth presenting once again at the next sprint review for everyone's thoughts on the new design

That's a good idea, the length was one thing we mentioned. We could for something shorter like what you mentioned. I was initially thinking of changing the design but having it with the correct padding makes it look better now.

**Comment by louise-davies** [comment]
Ah yeah, I meant to illustate a mock up - my bad! I thought perhaps something like this: https://codesandbox.io/s/button-demo-3l8t4?file=/demo.js

**Comment by GoelBiju** [comment]
> Ah yeah, I meant to illustate a mock up - my bad! I thought perhaps something like this: https://codesandbox.io/s/button-demo-3l8t4?file=/demo.js

Thanks @louise-davies for the example! I was looking as to how to center the `IconButton` with the text. We can maybe come to a decision as to which design in future meetings.
