### ISSUE TITLE
Add copy button to citation text in DOI landing pages

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#719]
**Description**:
Add an easy ways for users to copy the citation text in each of the landing pages.

**Acceptance criteria**:
- [x] Add copy button for the citation text in landing pages

**Comment by GoelBiju** [comment]
In order to complete this, I will need to:

- [ ] Add a method to generate the citation based on the information provided from components,
- [ ] Add a button copy the citation to the clipboard,
- [ ] Allow for visual confirmation of copy action.

**Comment by GoelBiju** [comment]
@agbeltran @louise-davies @sam-glendenning I have added in a copy citation button which works as shown below. Is the placement of the button on the study and the interaction on click fine?

![Animation](https://user-images.githubusercontent.com/16869075/124571266-8c1dc800-de3f-11eb-869a-301c5f7209d2.gif)

**Comment by sam-glendenning** [comment]
> @agbeltran @louise-davies @sam-glendenning I have added in a copy citation button which works as shown below. Is the placement of the button on the study and the interaction on click fine?
> 
> ![Animation](https://user-images.githubusercontent.com/16869075/124571266-8c1dc800-de3f-11eb-869a-301c5f7209d2.gif)

I quite like it! In other places I've seen copy buttons work, the copy button has remained greyed-out/unclickable after being clicked once, giving further indication to the user that they have copied the text and it remains in their clipboard. It stays like this until the user navigates away or refreshes. Is there a way to alter the behaviour to allow this? Even better if there was some way to tell if the text is no longer in the clipboard anymore so the button becomes clickable again (although I'm not sure if this is possible or even totally desirable).

**Comment by GoelBiju** [comment]
> > @agbeltran @louise-davies @sam-glendenning I have added in a copy citation button which works as shown below. Is the placement of the button on the study and the interaction on click fine?
> > ![Animation](https://user-images.githubusercontent.com/16869075/124571266-8c1dc800-de3f-11eb-869a-301c5f7209d2.gif)
> 
> I quite like it! In other places I've seen copy buttons work, the copy button has remained greyed-out/unclickable after being clicked once, giving further indication to the user that they have copied the text and it remains in their clipboard. It stays like this until the user navigates away or refreshes. Is there a way to alter the behaviour to allow this? Even better if there was some way to tell if the text is no longer in the clipboard anymore so the button becomes clickable again (although I'm not sure if this is possible or even totally desirable).

I did think about having the button disabled/greyed out when it is copied but the only issue would be that the user may want to copy it again. In that event, they would have to refresh or navigate to the page again. The other option would be to re-enable the button after a set time after it has been clicked. In that case, we could drop the tick animation and just have the button, I decided against it since you don't want to disable the button fully and make the user wait. At present, you can click it again and it will copy immediately to the clipboard. For telling if the text is already in the clipboard or not, I think we would need read permissions on the clipboard.
