### ISSUE TITLE
Link to RAW/Nexus data format

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#736]
**Description**:
Current DOI landing pages (as well as the new ones in DataGateway) contain a link for RAW/Nexus data format that does not exist anymore:
http://www.isis.stfc.ac.uk/groups/computing/isis-raw-file-format11200.html

See for example:
https://doi.org/10.5286/ISIS.E.24087891
and
https://datagateway.isis.stfc.ac.uk/browse/instrument/9/facilityCycle/3/investigation/24087891 

We need to check if the link needs to be replaced for a new link or totally removed.

**Acceptance criteria**:
- [x] Fix issue with link to RAW/Nexus data format

**Comment by agbeltran** [comment]
Adding screenshots.

<img width="1777" alt="Screenshot 2021-07-05 at 09 58 14" src="https://user-images.githubusercontent.com/1417033/124445533-8c529080-dd77-11eb-9034-3b0a6fa2a941.png">
<img width="1728" alt="Screenshot 2021-07-05 at 09 48 10" src="https://user-images.githubusercontent.com/1417033/124445544-8f4d8100-dd77-11eb-9c45-88b3621d9707.png">

**Comment by agbeltran** [comment]
Checking ISIS website, we could link to:
https://www.isis.stfc.ac.uk/Pages/ISIS-Raw-File-Format.aspx

or directly to https://www.nexusformat.org/

@srconway do you have a view on this or who to consult about updating (or removing) this link? Thanks

**Comment by srconway** [comment]
@agbeltran Anders Markvardsen or Dimitar Tasev might be able to advise on the correct link. I'm not sure I'm afraid.

**Comment by agbeltran** [comment]
thank you @srconway, we will contact them to ask about this
