### ISSUE TITLE
Add DOI link

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#737]
**Description**:
Even if it would point to the same page, I think it would be useful to add the DOI link on the landing page in the summary box to the right. Similarly on the citation text. 

**Acceptance criteria**:
- [x] Add DOI links
<img width="1728" alt="Screenshot 2021-07-05 at 09 48 10" src="https://user-images.githubusercontent.com/1417033/124446453-55c94580-dd78-11eb-8cad-0327c387c2ec.png">
 in the landing page

**Comment by GoelBiju** [comment]
@agbeltran I could add a hyperlink to the DOI in the citation text and the DOI in the summary which could open in a new page. I am currently with the study landing pages so I can add them to PR relating to copying citation #735.

**Comment by agbeltran** [comment]
Hi @GoelBiju - yes, that would be great

**Comment by GoelBiju** [comment]
@agbeltran @louise-davies @sam-glendenning I have added in a copy button which works as shown below. Is the placement of the button on the study and the interaction on click fine?

![Animation](https://user-images.githubusercontent.com/16869075/124571266-8c1dc800-de3f-11eb-869a-301c5f7209d2.gif)

**Comment by GoelBiju** [comment]
@agbeltran the ISIS investigation landing page with links looks like the following:

![image](https://user-images.githubusercontent.com/16869075/124625201-8347e900-de75-11eb-8f96-d30bdcb0cf59.png)

I am wondering if we need links on the DOIs for the datasets in the summary as well?
