### ISSUE TITLE
Rename master branch to main and start using dev branch

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#740]
**Description**:
Minor detail, but convention now is to have ```main``` as the primary branch on GitHub.

Easy steps here:
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Acceptance criteria**:
- [ ] Rename ```master``` branch to ```main```, put ```main``` as default, remove ```master```

**Comment by sam-glendenning** [comment]
Louise mentioned to check for references to 'master' in CI YAML files (or anywhere in code, if it happens to exist). If possible, change these to point to the default branch so we don't have to always name this branch in references

**Comment by GoelBiju** [comment]
> Louise mentioned to check for references to 'master' in CI YAML files (or anywhere in code, if it happens to exist). If possible, change these to point to the default branch so we don't have to always name this branch in references

In relation to this @sam-glendenning I saw this [StackOverflow](https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable) question which refers to getting the default branch in workflows.

**Comment by sam-glendenning** [comment]
Bit hacky but if it works it works

**Comment by GoelBiju** [comment]
@agbeltran @louise-davies @MRichards99 I saw this official repository by GitHub about renaming: https://github.com/github/renaming. They are suggesting using the web interface to recommend since it will update everything else in the repository. We might need to only update it in our local development environments.
