### ISSUE TITLE
In Study view, remove study.description and add investigation.title & add investigation dates

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#742]
**Description**:

In the study view, we are showing empty study.description column - we need to change it to show the investigation.title instead

Similarly the dates are empty and we should show the investigation dates (start date is the first experiment part start date).

<img width="2011" alt="Screenshot 2021-07-08 at 09 54 36" src="https://user-images.githubusercontent.com/1417033/124893927-164a6580-dfd3-11eb-8138-cf5938d7c2d8.png">

**Acceptance criteria**:
- [x] Showing columns with data in study (coming from investigation)

**Comment by GoelBiju** [comment]
@agbeltran I'll make the changes to the card view in addition to table as well.

**Comment by GoelBiju** [comment]
This has been addressed through #756.
