### ISSUE TITLE
In the Investigation list, remove visitID and only show it as part of the expanded metadata view

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#743]
**Description**:

The column Visit ID, which corresponds to the experiment part, is not so useful for the users so we should remove the column from the view.

<img width="2170" alt="Screenshot 2021-07-08 at 10 03 28" src="https://user-images.githubusercontent.com/1417033/124894813-e2bc0b00-dfd3-11eb-8f7a-066506dfce00.png">

https://datagateway.isis.stfc.ac.uk/browse/instrument/1/facilityCycle/1/investigation

We still need to show this info in the expanded metadata, but ```Investigation.details.visitId``` should be ```Experiment part```

<img width="2140" alt="Screenshot 2021-07-08 at 10 05 39" src="https://user-images.githubusercontent.com/1417033/124895105-257de300-dfd4-11eb-8fdb-6205b88680a1.png">

**Acceptance criteria**:
- [x] Remove visitID column
- [x] change label for visitId to experiment part

**Comment by GoelBiju** [comment]
@agbeltran I will remove "Visit ID" from the card summary information to make it consistent with the table as well.
