### ISSUE TITLE
Change URL label for Instruments to 'Information page'

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#744]
**Description**:

Change 'URL' to 'Information page'

<img width="1968" alt="Screenshot 2021-07-08 at 15 31 19" src="https://user-images.githubusercontent.com/1417033/124940083-92f43880-e001-11eb-89bb-b1b4c7277171.png">

**Acceptance criteria**:
- [x] Label changed

**Comment by louise-davies** [comment]
This is on master now
