### ISSUE TITLE
Allow Tab Access to "Show Advanced Filters"

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway#762]
**Description**:
On card view, a user who is only able to use a keyboard will be unable to access/click on the "Show Advanced Filters" link:
![image](https://user-images.githubusercontent.com/32678030/126633392-e690405d-39cc-4fec-8f3a-7e784189af43.png)

When you navigate the page using the tab key, you go from the card view toggle straight to the page number selector, missing out the filter link above it. 

Once the link has been clicked (I did this via my mouse), users can access all the filters inside it with no issues via keyboard only navigation.

Opened this issue as a result of #738 

**Acceptance criteria**:
- [x] Users should be able to focus on and interact with the "Show Advanced Filters" link by keyboard navigation only

**Comment by GoelBiju** [comment]
There were some tips in using the `Link` component from Material-UI [here](https://material-ui.com/components/links/#accessibility). The example code also highlights setting the `component` as a button which allows for tab-access instead of the default anchor element.
