### ISSUE TITLE
Text is not clear in dark mode for plugins

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#770]
**Description**:

The original issue applied to the "View My Downloads" button on `datagateway-download`. This was due to the text not being clear enough when the dark mode was enabled (as shown in the image below).

![image](https://user-images.githubusercontent.com/16869075/126917682-3f683b61-8f03-4d7b-b873-2cb19d456bcd.png)

The discussion below suggests it is worth checking all plugins to see where text does not contrast well with the background as @MRichards99 mentions in this [comment](https://github.com/ral-facilities/datagateway/issues/770#issuecomment-888139967).

**Acceptance criteria**:

- [ ] Text in `datagateway-dataview` is of appropriate colour/contrast in dark mode,
- [ ] Text in `datagateway-download` is of appropriate colour/contrast in dark mode,
- [ ] Text in `datagateway-search` is of appropriate colour/contrast in dark mode.

**Comment by GoelBiju** [comment]
The blue text on the dark background does make the text slightly harder to read in general on these table views.

**Comment by GoelBiju** [comment]
This is more of a usability question @MRichards99, we may not need to change this if it doesn't affect users but I thought I would mention it.

**Comment by MRichards99** [comment]
There's some automated checks via a browser extension that I'll do on the entire frontend once I've finished looking at it with a screen reader. These include looking at contrast ratio between different things of page, usually with a target ratio of 4.5:1 (3:1 for large text). We can both see this example is a problem, but I just ran the automated checks which says there's a ratio of 1.17:

![image](https://user-images.githubusercontent.com/32678030/127293991-85d280fc-57c0-48e7-988d-127e9e39affc.png)

It appears #80ACFF is used on the cart tab text and highlight, so maybe a lighter blue?
![image](https://user-images.githubusercontent.com/32678030/127294428-4e8eeea7-e716-419d-8ac0-5a22f22ac810.png)

Although based on the background colour as per the browser extension (#424242), it seems #85AFFF would give a constrast ratio of over 4.5:1 - this seems to be a helpful tool at a quick glance.

I agree this may be more of a general issue with dark mode so perhaps a more generic fix might be needed than just fixing this one issue? I don't know enough about how colours are used within the codebase at this point though

**Comment by GoelBiju** [comment]
> There's some automated checks via a browser extension that I'll do on the entire frontend once I've finished looking at it with a screen reader. These include looking at contrast ratio between different things of page, usually with a target ratio of 4.5:1 (3:1 for large text). We can both see this example is a problem, but I just ran the automated checks which says there's a ratio of 1.17:
> 
> ![image](https://user-images.githubusercontent.com/32678030/127293991-85d280fc-57c0-48e7-988d-127e9e39affc.png)
> 
> It appears #80ACFF is used on the cart tab text and highlight, so maybe a lighter blue?
> ![image](https://user-images.githubusercontent.com/32678030/127294428-4e8eeea7-e716-419d-8ac0-5a22f22ac810.png)
> 
> Although based on the background colour as per the browser extension (#424242), it seems #85AFFF would give a contrast ratio of over 4.5:1 - this seems to be a helpful tool at a quick glance.
> 
> I agree this may be more of a general issue with dark mode so perhaps a more generic fix might be needed than just fixing this one issue? I don't know enough about how colours are used within the codebase at this point though
> 
> Edit: the contrast tool - https://webaim.org/resources/contrastchecker/

A lighter blue seems a lot more readable than the darker one. Maybe we should make this issue more of a general one and address colours throughout all the plugins?

**Comment by MRichards99** [comment]
Agreed, once I've gone round DataGateway using the automated checks, we'll have a better understanding of exactly which colours need changing in dark mode so it'll probably be more efficient to do it all in one go?

**Comment by GoelBiju** [comment]
> Agreed, once I've gone round DataGateway using the automated checks, we'll have a better understanding of exactly which colours need changing in dark mode so it'll probably be more efficient to do it all in one go?

That makes sense, it's worth doing it all at once for all the plugins.

**Comment by sam-glendenning** [comment]
After speaking to Matt, I learned that we still need to decide exactly what else needs changing so I decided to add a commit that just changes the button as originally described (see https://github.com/ral-facilities/datagateway/commit/4bc52de876eca77c5f3435ada98a288ce5fc5eac). Button now looks like this (please excuse the lack of translations):

![image](https://user-images.githubusercontent.com/71134574/130604569-5d497e80-bc01-41cc-8f6d-defe12acd78c.png)

**Comment by louise-davies** [comment]
@sam-glendenning can you make a PR/draft PR for your branch?

**Comment by sam-glendenning** [comment]
[Made a PR](https://github.com/ral-facilities/datagateway/pull/820) to close the original issue as detailed in the issue description. This fixes the contrast issue with the button in the download confirmation box only. Other accessibility issues exist but these will be collated into a new issue later on.

**Comment by sam-glendenning** [comment]
https://github.com/ral-facilities/datagateway/pull/820 closes the originally stated problem of poor contrast in the download confirmation box. Any other contrast problems will have their own separate issues created later.
