### ISSUE TITLE
Improve Aria Labels on DataView

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway#772]
**Description**:
There's quite a few aria-label related improvements that could be made on DataView, so I'll collate them all into this issue. I'm guessing I'll spot things on Download and on Search so I'll create separate issues for those components when I get to them.

I won't include anything related to the view toggle switch, as that's being redesigned in #718 and I've spoken to @GoelBiju about having an aria label which is sensible for the final design of that.

**Acceptance criteria**:
- [x] Does whether the use of container in "container table search button" make sense to users? Decide and fix if not
- [ ] ~Add gaps to table view information~ (check if we want to fix this or not)
- [x] Remove duplication on text and date filter components
- [x] Resolve unneeded gap caused by "..." on include example text
- [x] Make cog aria label more sensible
- [x] Fix aria labels outputting on screen readers on the first row of data (row 2 in code)
- [x] Remove duplication on pagination navigation element
- [x] Make screen reader output on max results drop down less confusing
- [x] Remove "button button" when tabbing through card view sort by columns. This could be automatically be fixed through the solution of #763 
- [x] On date filters, add an appropriate aria label to make the calendar button functionality clear
- [x] The page view button has an aria label of 'page view button', which, when read by a screen reader, will say 'page view button button'. Remove the word 'button' in the aria label.
- [x] The dates are read as 'start date date filter from edit from... (yyyy-MM-dd)', which sounds jarring. The 'start date date filter from' section is the aria label followed by the placeholder text 'from... (yyyy-MM-dd)'. We can't find a way of not making the placeholder text be read aloud so this is hard to fix right now
- [x] doi is pronounced as doy 
- [x] investigate inconsistencies with tab selecting from dropdown lists. Currently, it seems like tabbing to a dropdown requires you to press space to open the dropdown and then either space or enter to start interacting with it before requiring enter to be pressed to select an option
- [x] Focusing on data in the table using tabs sometimes allows for the screen reader to read out "grid grouping" or read the whole data in the table

**Comment by MRichards99** [comment]
![image](https://user-images.githubusercontent.com/32678030/127497885-4cce371b-7304-4ca8-b7dd-6dc498cb5dc5.png)

When focused on and using a screen reader, the search and cart buttons are outputted as 'container table search button' and 'container table cart button' (defined by aria labels). Does the word container make sense to users? As a developer, I understand container means either table or card view, but is that clear to a user?

**Comment by MRichards99** [comment]
When tabbing around the page, the first focus on table view is when you get to the select all rows checkbox. When this happens, quite a bit of information is given to the user all at the same time, at quick pace:
"table with 50 rows and 10 columns  row 1  select all rows  column 1  clickable  select all rows  check box  not checked"

This is useful information but needs to be separated up a bit. In the first instance, full stops should be used at the end of the aria labels to give a bit of gap between each piece of information, or maybe using `aria-labelledby` might help, so there's a defined relationship between different components on the page - https://stackoverflow.com/a/55273574/8752408

**Comment by MRichards99** [comment]
Tabbing to a text filter component (screenshot below), the following text is read to the user: "Title Filter by Title   Column 3  Title button"

![image](https://user-images.githubusercontent.com/32678030/127513578-75c3294d-cf0e-418e-a540-b8e4595f4216.png)

There's a bit of duplication there with the filter label which could be reduced. The "Title button" could be made clearer - sort by title button perhaps?

**Comment by MRichards99** [comment]
When focusing on the text field, a screen reader dictates: "Include    edit blank"
![image](https://user-images.githubusercontent.com/32678030/127514022-52519636-257b-4fae-b0d6-3154449877c2.png)

Due to the '...' in the include, there's a delay between "include" and "edit blank" which could confuse some users.

**Comment by MRichards99** [comment]
When focusing on the cog, the screen reader dictates "clickable menu button  sub menu". This doesn't describe the functionality of it. Using dev tools, I can see that element has `aria-labelledby="select-filter-type"`. Maybe changing this to a regular aria-label might fix this issue (select filter type adequately describes the functionality).

![image](https://user-images.githubusercontent.com/32678030/127514670-4135a1ba-22c3-4fa1-a22b-892812234ee8.png)

**Comment by MRichards99** [comment]
For reference, the issues I've just raise also added in comments also impact date filters.

**Comment by MRichards99** [comment]
When tabbing through the page, on the first row of data, none of the aria-label register with the screen reader i.e. I'm not being told anything and just sit here in silence. They work on the second row onwards (row 3 in code). I can shift tab back to the first data row and then those will work too. I'm not quite sure why this is, needs further investigation.

![image](https://user-images.githubusercontent.com/32678030/127517421-36c3d92a-58e6-44df-9a5f-fbe38414a61f.png)

**Comment by MRichards99** [comment]
On card view, tabbing to the pagination navigation nets you the following from the screen reader: "pagination navigation navigation ........". Not a major thing, but the duplicate navigation shouldn't happen.

![image](https://user-images.githubusercontent.com/32678030/127520444-512f82bd-9af8-4c7f-8a5d-a185e9f46b4a.png)

**Comment by MRichards99** [comment]
Focusing on the max results drop down gives the following from the screen reader - "clickable max results 10 menu button sub menu". This isn't the clearest - maybe dropping the "sub menu" might make more sense?

![image](https://user-images.githubusercontent.com/32678030/127520780-afbab7ae-9166-4849-901f-63ca8839c104.png)

**Comment by MRichards99** [comment]
When tabbing through the sort by columns, the second tab nets "button button". This shouldn't output on a screen reader, the first tab gives useful information. This is linked to and the cause of #763 

![image](https://user-images.githubusercontent.com/32678030/127523690-38cc033e-6f92-41bf-b10d-41c90f6a2af4.png)

**Comment by MRichards99** [comment]
Note that DOI is pronounced "doy". That could just be my screen reader and probably not much that can be done on DataGateway's side, but something to note nonetheless.

**Comment by GoelBiju** [comment]
> When tabbing through the sort by columns, the second tab nets "button button". This shouldn't output on a screen reader, the first tab gives useful information. This is linked to and the cause of #763
> 
> ![image](https://user-images.githubusercontent.com/32678030/127523690-38cc033e-6f92-41bf-b10d-41c90f6a2af4.png)

This has been resolved by #795.

**Comment by GoelBiju** [comment]
> ![image](https://user-images.githubusercontent.com/32678030/127497885-4cce371b-7304-4ca8-b7dd-6dc498cb5dc5.png)
> 
> When focused on and using a screen reader, the search and cart buttons are outputted as 'container table search button' and 'container table cart button' (defined by aria labels). Does the word container make sense to users? As a developer, I understand container means either table or card view, but is that clear to a user?

I have changed the naming now to remove container from the beginning of these labels. Having container does not make sense to a user.

**Comment by MRichards99** [comment]
Just want to link this issue to the original reason this was created (#738)

**Comment by MRichards99** [comment]
I've just noticed something else with the date filters. This issue contains lots of work for the filters on table view so it seems appropriate to add this here rather than create a new issue.

When using a screen reader and focused on the button that opens the calendar view thing (not sure what it's proper name is), the screen reader just outputs "button". It looks like there's no aria label present, so one should be added to make the button's functionality clear
![image](https://user-images.githubusercontent.com/32678030/129557753-497788f1-417e-4b0b-8624-e11c5b0d896c.png)

**Comment by sam-glendenning** [comment]
Hi @AkhilMag13 I'm assigning you to this since Goel started but didn't finish it. This should give you something else to do for this sprint. Best to work through the checklist in the issue description and tick things off as you go. Let me know of any issues!

**Comment by AkhilMag13** [comment]
> When focusing on the text field, a screen reader dictates: "Include edit blank"
> ![image](https://user-images.githubusercontent.com/32678030/127514022-52519636-257b-4fae-b0d6-3154449877c2.png)
> 
> Due to the '...' in the include, there's a delay between "include" and "edit blank" which could confuse some users.

I have fixed this by removing the '...' from the include and now the screen reader does not have the delay. Sam and I have also tried to include an aria-label to fix this problem without removing the ellipses, but that has not worked out yet. Any additional solutions are welcome.

**Comment by sam-glendenning** [comment]
> When focusing on the cog, the screen reader dictates "clickable menu button sub menu". This doesn't describe the functionality of it.

I've now changed this in https://github.com/ral-facilities/datagateway/commit/ee6908175eb47a36ed21e03911fbec8b26fb574a to say "clickable select filter type menu button sub menu". This is a marginal improvement, with the potential to be made better later on.

**Comment by sam-glendenning** [comment]
> On card view, tabbing to the pagination navigation nets you the following from the screen reader: "pagination navigation navigation ........". Not a major thing, but the duplicate navigation shouldn't happen.

This is now fixed by https://github.com/ral-facilities/datagateway/commit/80758a24f2271992bd1b35189339fe069119fc1c

**Comment by AkhilMag13** [comment]
> Focusing on the max results drop down gives the following from the screen reader - "clickable max results 10 menu button sub menu". This isn't the clearest - maybe dropping the "sub menu" might make more sense?
> 
> ![image](https://user-images.githubusercontent.com/32678030/127520780-afbab7ae-9166-4849-901f-63ca8839c104.png)

This is an ongoing problem with regards to NVDA as the screen reader is reading the component's name along with the labels provided. This resulted in another problem being found where the dropdown options are not accessible using keyboard shortcuts and the options are also being read as blank.

**Comment by sam-glendenning** [comment]
> Note that DOI is pronounced "doy". That could just be my screen reader and probably not much that can be done on DataGateway's side, but something to note nonetheless.

This has been fixed in https://github.com/ral-facilities/datagateway/commit/399b4781c8932cc5c3992e399c2734ff043d56cd

**Comment by sam-glendenning** [comment]
> When using a screen reader and focused on the button that opens the calendar view thing (not sure what it's proper name is), the screen reader just outputs "button". It looks like there's no aria label present, so one should be added to make the button's functionality clear

This has been fixed in https://github.com/ral-facilities/datagateway/commit/423787e02a837b4f616f78e8ab541adf7a9917ec. Screen reader now says 'Start date filter from date picker button'.

**Comment by GoelBiju** [comment]
@MRichards99 we wanted to run these changes by you (in PR #813) to get your review on the progress so far

**Comment by MRichards99** [comment]
@GoelBiju I'll look at the PR tomorrow (2/9). I see the PR is in draft state, is that just because the testing are failing/need to be fixed or is there further work to be done on it?

**Comment by GoelBiju** [comment]
> @GoelBiju I'll look at the PR tomorrow (2/9). I see the PR is in draft state, is that just because the testing are failing/need to be fixed or is there further work to be done on it?

Sure no problem 😃, the tests are failing but I have mentioned the fix to @AkhilMag13 in a small review of the code on the PR. Aside from that everything else is implemented for this issue (with the exception to the table description which we have omitted for the time being, this can become a new issue if it is required).

**Comment by AkhilMag13** [comment]
The "Display as Table/Cards" button was being read as "Page-view button" on the screen reader, which offers very little description of the functionality of the button. 
![image](https://user-images.githubusercontent.com/88283659/131658474-c21ad320-9ca1-4834-9c38-4144f3744108.png)
I have fixed this issue 6af5cda2 by modifying the aria label to contain the ternary statement, based on the text of the button. Now it is read as "Page-view Display as table button" and "Page-view Display as cards button" respectively.

**Comment by GoelBiju** [comment]
> The unit tests on all plugins also need updating due to changes to the date filter.

The unit tests have been fixed now and all that needs correcting are end-to-end tests. These can be addressed once PR #813 has been reviewed.

**Comment by GoelBiju** [comment]
A small item that we may want is the ability to focus on column headers that do not have sorting/filtering. An example of this is "Dataset Count" which at the moment is just an icon and text. You cannot currently tab to the column header and will just skip over it when you try to. The only issue at the moment is how the tabbing should be configured, using `tabIndex` produces a variety of results with the NVDA screen reader which is sometimes accurate but most of the time not with duplicate information (as @sam-glendenning has mentioned).

**Comment by GoelBiju** [comment]
> A small item that we may want is the ability to focus on column headers that do not have sorting/filtering. An example of this is "Dataset Count" which at the moment is just an icon and text. You cannot currently tab to the column header and will just skip over it when you try to.
> 
> The only issue at the moment is how the tabbing should be configured, using `tabIndex` produces a variety of results with the NVDA screen reader which is sometimes accurate but most of the time not with duplicate information (as @sam-glendenning has mentioned).

I'll create this as a separate issue in order to not hold this issue up.
