### ISSUE TITLE
Minor fixes to EntityCard/CardView

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#815]
**Description**:

There are some small issues that I wanted to address with the `EntityCard` and `CardView` components.

**Acceptance criteria**:

- [x]  the paper background which is apparent when dark mode is turned on,

- [x] the dividers for summary information which appears when the information array/prop is empty (could also be an issue with buttons array/prop),

- [x] ~hide pagination/filters/sort options when no results are loaded~ (this might not be useful anymore since we only really want to update the cards themselves on page/sort/filter changes, otherwise we do not want to show it when there are no results),

- [x] ~do not show advanced filters when data isn't loaded yet~ (it might be best to not let props like `totalDataCount` or `loadedData` control when the `AdvancedFilters` component is shown just for usability as it continues staying open for the user),

- [x] ~advanced filters jumping when no data is present and when data is loaded~ (this doesn't appear to be an issue)

- [x]  when a user changes pages, only change the cards themselves and not the rest of the UI (as mentioned by @louise-davies),

- [x] hide the no results message when loading data, only show it once loading has been performed and the `totalDataCount` is 0,

- [x] check filtering/no results message,

- [x] selecting filtering options hides all of the UI components until the `totalDataCount` is greater than zero; this is since all of the UI elements will hide based on `totalDataCount` (addressed by adding a `filterUpdate` prop which prevents the UI from hiding on a filter change),

- [x] ~"sort by" box does not reflect the summary information displayed on the card itself, shows all objects regardless if data is shown or not?~ (maybe we cannot control this since data for one card may not be shown but others will have it, sorting should work fine regardless if one card does not show the information for it unless we show a "N/A" if the specific information content to show for that card is empty): https://github.com/ral-facilities/datagateway/blob/fcae11c92d5440061eb41bf7550d60f9ff69fa37/packages/datagateway-common/src/card/entityCard.component.tsx#L217

- [x] ~investigate if advanced filters need icons defined, can we just pass them through as props from card view~ (crossing this off for now but it might be worth thinking about having the information needed to render the correct icon passed through to the advanced filter rather stating a list of icons to choose from): https://github.com/ral-facilities/datagateway/blob/fcae11c92d5440061eb41bf7550d60f9ff69fa37/packages/datagateway-common/src/card/advancedFilter.component.tsx#L67

- [x] fix "undefined" prop warnings when running unit tests on `datagateway-dataview`,

- [x] card chips do not load any information at the moment (or disable them for now); **fixed by adding an "include" filter to the data request which fetches the "type" and "facility"**,

- [x] better aesthetically to have the chips show above the more information or below it? (it looks better to keep it as it is since the "more information" section being above the tags associates the section with the rest of the information in the card),

- [x] it might be ideal to show instruments with chips/tags since then you can filter by the type e.g, "crystallography" (this can be an issue or feature request at a later point if needed),

- [x] add support for ~icons/avatar in chips, colour and~ prefixing the label name before the data (at present having an icon and changing the colour is not a requirement, changing the color is not supported through the `color` prop either but can be done through by changing `backgroundColor` in inline CSS although this is not as good as if it is supported),

- [x] check status of #265 to see if we can implement this (this has been now implemented in https://github.com/ral-facilities/datagateway/commit/fdc68cee98ee4e49c4b3a2c0c4ed9303e84808fa).

**Comment by louise-davies** [comment]
When a user resorts/goes to next page etc all the UI pretty much disappears, when maybe it's better just the cards themselves do?

**Comment by GoelBiju** [comment]
> When a user resorts/goes to next page etc all the UI pretty much disappears, when maybe it's better just the cards themselves do?

I have addressed this @louise-davies, the only situation where it will occur is when you select a filtering option, this is due to the UI elements rendering based on the `totalDataCount`. The other solution might be to prevent the UI hiding when filtering options are selected but we would also still need to handle when, after `loadedData` is true, if any data has been returned or not.

**Comment by GoelBiju** [comment]
@louise-davies @sam-glendenning a couple of issues I recognised were with how we handle the search query parameters. 

The first is that the "results" query can be changed to any value irrespective of the max results dropdown in card view. This is due to the fact in `useInvestigationsPaginated` we parse the query for "results" and use that in the API request. This isn't an issue for the table view since it uses the offset params but in the card view, a user can set this to outside the default 10, 20, and 30 or a custom `resultOptions` for the `CardView` component.

The second item is that the "page" and "results" query parameters are kept even when changing views from card to table. This isn't much of an issue since we only use the parameters we need to but I am guessing this is because we no longer the saved queries in Redux anymore after moving to react-query?

**Comment by sam-glendenning** [comment]
Are you talking about how the pagination breaks when the user sets their own value for the results parameter? Yes, I'd never noticed that. We'd need a fix for it. As for the second one, yeah those parameters stick around and have done for a while but I don't see anything wrong with keeping them in. If the user were to change back to the original view, they'd at least get to keep their applied settings.

**Comment by GoelBiju** [comment]
> Are you talking about how the pagination breaks when the user sets their own value for the results parameter? Yes, I'd never noticed that. We'd need a fix for it. As for the second one, yeah those parameters stick around and have done for a while but I don't see anything wrong with keeping them in. If the user were to change back to the original view, they'd at least get to keep their applied settings.

Yeah, the pagination does break when the user sets their own value. I'll create a separate issue for this.

The second one isn't an issue at all but I had remembered before when we were saving the queries in the Redux state according to which view they were created in.

**Comment by GoelBiju** [comment]
> > Are you talking about how the pagination breaks when the user sets their own value for the results parameter? Yes, I'd never noticed that. We'd need a fix for it. As for the second one, yeah those parameters stick around and have done for a while but I don't see anything wrong with keeping them in. If the user were to change back to the original view, they'd at least get to keep their applied settings.
> 
> Yeah, the pagination does break when the user sets their own value. I'll create a separate issue for this.
> 
> The second one isn't an issue at all but I had remembered before when we were saving the queries in the Redux state according to which view they were created in.

The issue regarding the results query parameter is now being tracked by #831.

**Comment by GoelBiju** [comment]
@louise-davies, I am currently facing an issue with the e2e tests where the card contents is failing to match [here](https://github.com/ral-facilities/datagateway/blob/2a7888755b31bc3b1f292439321e71c0af7ca342/packages/datagateway-dataview/cypress/integration/card/investigations.spec.ts#L92). I cannot seem to pinpoint why this is occuring even though the card appears correctly on the page. I am wondering if it is due to the filter changes since it requires the "Type ID - 1" filter being applied. I have skipped it for the time being.

**Comment by GoelBiju** [comment]
> @louise-davies, I am currently facing an issue with the e2e tests where the card content is failing to match [here](https://github.com/ral-facilities/datagateway/blob/2a7888755b31bc3b1f292439321e71c0af7ca342/packages/datagateway-dataview/cypress/integration/card/investigations.spec.ts#L92). I cannot seem to pinpoint why this is occurring even though the card appears correctly on the page. I am wondering if it is due to the filter changes since it requires the "Type ID - 1" filter to be applied. I have skipped it for the time being.

@MRichards99 has addressed this by changing the data we are testing for in https://github.com/ral-facilities/datagateway/commit/41eba936aad6298f8488daa38fac5f558865f698.
