### ISSUE TITLE
Use givenName and familyName fields for Users instead of fullName if they are not null

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#817]
**Description**:
ISIS is starting to move to use givenName and familyName rather than the fullName field for Users. We need to support this.

Note: ensure this doesn't affect DLS (I presume they're just not filling those fields - otherwise we may need a settings toggle to say which field to use)

Note: is there any concerns about internationalisation & localisation regarding this? Or do we just format everything in the "English" format

**Acceptance criteria**:
- [ ] Use `givenName` and `familyName` fields if they exist
- [ ] Ensure this change only affects ISIS - if DLS fills those fields in then a setting will be needed to ensure both ways (`fullName` preferred vs `givenName` `familyName` preferred are possible)

**Comment by WHTaylor** [comment]
Hey just to clarify - we're not planning to stop using `fullName`, we'll just also be filling in the `givenName` and `familyName` fields so they're available if useful for anything. On our end, we're planning to sort the names on DOI landing pages by family name, but still display the full name, for example.

`fullName` will continue to include some info that aren't in the other fields (ie. title), so is probably the best display name in many cases.

**Comment by sam-glendenning** [comment]
Hi @WHTaylor, I'll be the one tackling this. As I understand it, you'll be populating more `givenName` and `familyName` fields but `fullName` will continue as the main display name for instruments/facilities, etc. With that in mind, are there any changes you want me to make with column names, fields that you can sort and filter by, etc? Or is this more to allow for given and family names to display in details panels?

**Comment by WHTaylor** [comment]
I don't know how the data gateway is currently using this data, so it's hard to say what would be good. From the ISIS ICAT side,  we're just making these two fields available as extra options (at the moment they're always empty) so they can be used if needed/it makes sense to. If you're happy with using `fullName` everywhere, that's absolutely fine - we're mostly putting it in for the sorting on the DOI pages I mentioned above, at least for now.

**Comment by sam-glendenning** [comment]
@louise-davies by the sounds of it, what Will is suggesting doesn't seem to require anything done as our current usage of fullName seems to be the most useful information to give to the end user. Maybe just double checking that givenName and familyName are shown in details panels when provided and close the issue?
