### ISSUE TITLE
[all?] Internationalisation

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#84]
The breadcrumbs code review brought up that entities were being pluralised using the letter 's' - this is obviously English specific and should be handled by an internationalisation library/component. Additionally, `datagateway-table` currently hard codes its strings - this can also be fixed by an internationalisation library/component

Acceptance criteria:
- [ ] Internationalisation library is used to pluralise entity names
- [ ] Internationalisation library is used to provide alternate language settings for strings

**Comment by GoelBiju** [comment]
These are two libraries to possibly be used for this particular issue: [i18next](https://www.i18next.com/) and [polyglot.js](https://airbnb.io/polyglot.js/).

**Comment by louise-davies** [comment]
Additionally there's [`react-intl`](https://github.com/formatjs/react-intl)
