### ISSUE TITLE
Citation formatter

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#868]
**Description**:
Currently on the landing pages, we have a recommended citation format and have a 'copy to clipboard' option.

It would be great to add a citation formatter relying on the API by datacite:
https://support.datacite.org/v1.1/docs/datacite-citation-formatter

that should work as in 
https://citation.crosscite.org/

so, I suggest that - in addition to the current recommended citation format - we add an option to choose the formatting style (a dropdown list of styles) and show the citation with a copy to clipboard option too

**Acceptance criteria**:
- [ ] DOI landing pages give the option to copy the citation in different formats

**Comment by joelvdavies** [comment]
![image](https://user-images.githubusercontent.com/90245114/144435083-d58dfa0d-d0e1-40ca-9b49-89715ed43457.png)
Still a work in progress, just duplicated the heading and content to start with. Should the formatter be under a different heading like Data Citation Formatter, or add the customisable citation directly under the original one?

**Comment by joelvdavies** [comment]
@agbeltran For reference I have currently added 
![image](https://user-images.githubusercontent.com/90245114/145565776-e6cf4bd9-d8c1-4b37-abda-37ec239ff99a.png)
and the possible formats are listed here https://github.com/citation-style-language/styles, although they should also be accessible through https://citation.crosscite.org/.

**Comment by agbeltran** [comment]
Thanks @joelvdavies - that's looking great.

Please, add

- american-physics-society
- american-chemical-society
- american-institute-of-physics
- nature
- institute-of-physics-numeric

Remove 
- ieee

Thanks!
