### ISSUE TITLE
Configuration of labels in detailed view of search results/table

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#870]
**Description**:
It seems that the search results table is missing the configurations of labels in the detail view (see screenshot), as the variable names are visible

<img width="1877" alt="Screenshot 2021-10-21 at 22 16 08" src="https://user-images.githubusercontent.com/1417033/138358038-a0822c33-808a-4adc-8f06-4de656eefa7c.png">

**Acceptance criteria**:
- [ ] Configure labels in detail view for search results table.

**Comment by louise-davies** [comment]
I had left out a language file update - this is now fixed on the deployed machines
