### ISSUE TITLE
Browser title and favicon

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#873]
**Description**:
We should change the browser title to DataGateway. The favicon will also need changing for the Diamond instance.

<img width="571" alt="browser-title" src="https://user-images.githubusercontent.com/1417033/138412162-ce62295f-8cf1-468c-923a-d672fe43616f.png">

**Acceptance criteria**:
- [ ] change browser title and favicon

**Comment by joelvdavies** [comment]
Spoken to @louise-davies, I will modify the title to be configurable in SciGateway (https://github.com/ral-facilities/scigateway/issues/789), and Louise will make the favicon configurable.

**Comment by agbeltran** [comment]
@louise-davies is this blocked?

**Comment by louise-davies** [comment]
Fixed via https://github.com/ral-facilities/scigateway-ansible/commit/4c34fd0004fd990f950db1fb505b1e7be0fce924
