### ISSUE TITLE
Links to hierarchy in search results not available

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#879]
**Description**:
When searching by dates (see screenshot) there are:
- multiple investigation results with no links to see the hierarchy (datasets, etc)
- multiple dataset results with no links to see the hierarchy (datafiles)

These seems to be calibration datasets so it might be a problem with the metadata.

<img width="1289" alt="Screenshot 2021-10-22 at 18 34 56" src="https://user-images.githubusercontent.com/1417033/138499021-7d27a9a8-557d-42d9-95ec-08b09d1a4a9f.png">

<img width="1298" alt="Screenshot 2021-10-22 at 18 36 17" src="https://user-images.githubusercontent.com/1417033/138499037-4b304d4e-a31a-4a6b-a759-1457243312b0.png">
**Acceptance criteria**:
- [ ] investigate and resolve the issues with no links /hierarchy in investigations/datasets

**Comment by louise-davies** [comment]
This issue was fixed via the facility cycles fix ISIS implemented
