### ISSUE TITLE
Add ability to fetch sizes with investigations & datasets

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#9]
Currently, `fetchInvestigations` and `fetchDatasets` only support the additional querying of file counts which is fine for Diamond, but ISIS requires the ability to query for file size calculations.

Acceptance criteria:
- [x] `fetchInvestigations` and `fetchDatasets` can retrieve `getSize` calculations

**Comment by GoelBiju** [comment]
Currently this is being blocked by #89 . We need toget the specific state related code to be merged in before continuing.

**Comment by GoelBiju** [comment]
The code for fetchInvestigationSize and fetchDatasetSize has been added, I need to write up the tests related to the investigations, datasets and reducers.
