### ISSUE TITLE
Contrast not compliant with WCAG 2.1

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/datagateway#905]
**Description**:
This is a general issue for contrast not meeting WCAG 2.1 standards. See the corresponding SciGateway one here: https://github.com/ral-facilities/scigateway/issues/795.

**Acceptance criteria**:
- [ ]  Contrast issues fixed

**Comment by louise-davies** [comment]
With the addition of the high contrast mode, we think this issue has been resolved
