### ISSUE TITLE
The contrast on instruction for tick boxs don't satisfy WCAG 2.1 

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/datagateway#911]
**Description**:

The contrast on instruction for tick boxs don't satisfy WCAG 2.1 

![search](https://user-images.githubusercontent.com/83226114/140774729-5ecbf5a6-2436-403b-8712-cd6163669a12.gif)

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by joelvdavies** [comment]
@joshuadkitenge I would recommend using the red/blue I added to SciGateway via `(theme as any).ukri?.contrast?.red/blue`  so they match everything else.
