### ISSUE TITLE
Add links to homepage

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/datagateway#943]
**Description**:
Related to https://github.com/ral-facilities/scigateway/issues/820. The labels and images on the homepage should be links that redirect to browse, search and download views.

**Acceptance criteria**:
- [ ] Labels and images redirect to browse/search/download views

**Comment by agbeltran** [comment]
@joelvdavies I will provide new text for the description of the funcionality, so perhaps you can add it to the PR related to this issue
