### ISSUE TITLE
Investigate the limit of 300 search results and improve it

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#948]
**Description**:
We currently have a limit of 300 search results and this needs to be revised in the future.

**Acceptance criteria**:
- [ ] Eliminate search limit

**Comment by louise-davies** [comment]
As a result of some problems in DLS, it's been proposed that they would like a lower limit. We should make this configurable

**Comment by louise-davies** [comment]
This needs to also configure the help text saying the amount of results returned
