### ISSUE TITLE
Change daaas naming in packages to scigateway

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#95]
**Description**
Similar to the [issue](https://github.com/ral-facilities/scigateway/issues/110) in the scigateway, instances of daaas/daaas-frontend in the scigateway source code will be changed to scigateway once the pull request for that issue is approved.

We need to do the same for datagateway packages (table, search and download) to ensure that there are no issues when running the plugins with the parent application.

**Acceptance Criteria**

- [x] Occurences of `daaas` or `daaas-frontend` are changed to `scigateway` in all datagateway plugins/packages.

**Comment by GoelBiju** [comment]
I wondering if these namings in packages should be either defined in the settings or within a single location @louise-davies . It would make altering it in the future easy that renaming?

**Comment by louise-davies** [comment]
Yeah, it should probably be defined in `common` and imported in. It's unlikely it will change in the future but it's best just in case.

**Comment by GoelBiju** [comment]
All the occurences of daaas/daaas-frontend have been changed in the packages except for specific 'daaas:token' references which will be altered by @louise-davies when we move to using the `scigateway` JWT token.
