### ISSUE TITLE
Replace instrument column in ISIS browse view with principle investigator column

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#975]
**Description**:
Replace instrument column in ISIS browse view with principle investigator column

**Acceptance criteria**:
- [x] Column Instrument replaced by Principal Investigator

**Comment by agbeltran** [comment]
The instrument column is now repeating the instrument name, so it would be better to include the PI instead.

See screenshot:
<img width="1242" alt="Screenshot 2021-12-07 at 16 58 43" src="https://user-images.githubusercontent.com/1417033/145072976-5fbd96ab-75d5-4922-aab5-961fa45bba9b.png">

**Comment by louise-davies** [comment]
This requires knowing what the `role` meaning PI is. This is `principal_experimenter` in ISIS prod.

**Comment by AkhilMag13** [comment]
@agbeltran Currently, the `principal_experimenters` can be seen on certain investigations, but in investigations where there are no PIs, should it be left blank as shown or say `None` or @louise-davies suggested for it to be an italicised _`No Principal Experimenter`_?

![image](https://user-images.githubusercontent.com/88283659/146002590-d0f136ff-9695-4f9d-9ec8-ca0520674c2e.png)

**Comment by agbeltran** [comment]
thanks @AkhilMag13 - in this case I suggest we leave it as blank, as in other rows in the table, when there is no data it is clear
