### ISSUE TITLE
Display "No publications" when there are no publications

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#982]
**Description**:
The dialogue looks like something is wrong/something hasn't loaded when in fact there's just no publications associated. Perhaps this should also be extended for all the "lists of items details panel tabs" as well - it's just worse with publications because there's often none.

**Acceptance criteria**:
- [ ] There's a "no publications" message displayed when there are no publications associated with an investigation in the details panel

**Comment by joshuadkitenge** [comment]
Adding this feature to the "investigation samples" and the "investigations users".
