### ISSUE TITLE
Inherit theme options from SciGateway

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#99]
**Description**:
The new UKRI brand guidelines (https://www.ukri.org/about-us/brand-guidelines/) detail new colour palettes that STFC should be using. Additionally, we'll need to change the favicon to be the new logo.

Update: this issue should investigate inheriting any theme from SciGateway

**Acceptance criteria**:
- [x] SciGateway uses new UKRI/STFC colour palette
- [x] ~SciGateway favicon is the new logo~

**Comment by GoelBiju** [comment]
@agbeltran I don't know if we need to update the favicon for the plugins since it will be using the SciGateway one?

**Comment by GoelBiju** [comment]
This issue will also require the new logo for DataGateway once the design has been confirmed.

**Comment by GoelBiju** [comment]
> This issue will also require the new logo for DataGateway once the design has been confirmed.

Adding a new favicon/logo to DataGateway will be addressed by #262.

**Comment by GoelBiju** [comment]
The `DGThemeProvider` can be added to `datagateway-search` once #307 has been merged into master, allowing for master to be merged into the data-search branch.
