### ISSUE TITLE
Download page with no selections

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#996]
**Description**:
If a user goes to the download page without having selected any item, the table is displayed empty (with 'remove all' button enabled). I suggest we add some explanation that they should use either browse or search to select items for download.

**Acceptance criteria**:
- [ ] Add clarifications and buttons leading to search and download if the download page is open without any selection

**Comment by agbeltran** [comment]
As discussed this morning, no need to show the table headers if the table is empty. @mattjSTFC will see to provide a wireframe.

**Comment by mattjSTFC** [comment]
Here's a potential solution which has all redundant content hidden if no data is selected:

https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/145099940/comment/sitemap

This would involve hiding the filters, number of files, total size two CTAs until data has been selected.

**Comment by agbeltran** [comment]
thank you @mattjSTFC! That looks great. Only that I would also add the option of 'Search data' as the two ways of selecting data is via browsing or searching. Could you please add that? Thanks!

**Comment by mattjSTFC** [comment]
Do you know if DG has a secondary button colour option? In an ideal world it's advisable not to offer two primary options in one place as it can make for confusion about where to go. In DAFNI we have a full block colour button as a primary action and the secondary button is an outline.

**Comment by mattjSTFC** [comment]
I've added 5 options with notes to UXPin of ways it could be done.

**Comment by agbeltran** [comment]
thanks @mattjSTFC - the different options look great! I would say that the secondary button colour option si that one of the 'Sign in' button.

**Comment by agbeltran** [comment]
I like options 2 or 5. Perhaps 5 fits better with the notifications about selections?

**Comment by agbeltran** [comment]
We might need to consider the option of a secondary button, and update it across the site, such as in the download cart:

<img width="387" alt="Screenshot 2021-12-13 at 18 42 41" src="https://user-images.githubusercontent.com/1417033/145869733-79c993fa-c688-4fd9-89e3-a637df36e6fc.png">

**Comment by mattjSTFC** [comment]
Yes I think that would be a good idea but maybe something to consider when there is an opportunity to look at the entire platform so not to add individual changes but make updates as a collective.

**Comment by mattjSTFC** [comment]
Maybe go with option 5 for now until a decision is made on other changes such as primary and secondary CTAs. It certainly is the simplest and nice and light.

**Comment by joelvdavies** [comment]
@agbeltran @mattjSTFC We don't currently do it but It should be simple to override the secondary button colour in SciGateway and then it would be usable in DataGateway.

**Comment by agbeltran** [comment]
@joelvdavies if you think it can be changed in SciGateway easily and inherited in DataGateway, let's go with the secondary button colour (as that would be the collective soluton). Otherwise, ok to use option 5 for now as @mattjSTFC suggets

**Comment by joelvdavies** [comment]
@agbeltran What should the secondary button colour be? The blue of the sign in button or the one in option 2. Also do you still want option 5 or would this change things?

**Comment by agbeltran** [comment]
This is looking great! But we want to make more visible that 'Browse' and 'search' are links.

**Comment by agbeltran** [comment]
In the mockup, option 5, this is done by putting the letters in bold: https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/145105838/comment/sitemap
